#字典和样式等服务
service.addr=/myservice/
#service.addr=http://127.0.0.1:88/myservice/
#数据密码，用户对字段密码进行二次加密，核心密码。
data.password=123asdzxc
sjzt.mm.ejmm=5zIcmw5qVZs=
yhxx.yhmm.ejmm=YA3EPe3fj/XrUtXDBr0y/Q==
app.mm.ejmm=YA3EPe3fj/XrUtXDBr0y/Q==

#default数据源
default.jdbc.url=jdbc:oracle:thin:@127.0.0.1:1521:mydb
default.jdbc.username=sjsj
default.jdbc.password=sjsj

#web.init.classList=cn.benma666.bdhc.ZlbdHmbd,cn.benma666.km.job.KmWebInit