
sys.sclj = /tmp/upload/
sys.sclb=LOCAL

#default数据源
#jdbc.driver=oracle.jdbc.driver.OracleDriver
jdbc.url=jdbc:oracle:thin:@127.0.0.1:1521:mydb
jdbc.username=yzqqb
jdbc.password=yzqqb

#字典和样式服务
service.addr=/myservice/

#druid datasource
druid.initialSize=2
druid.minIdle=2
druid.maxActive=50
druid.maxWait=60000
druid.timeBetweenEvictionRunsMillis=60000
druid.minEvictableIdleTimeMillis=300000
druid.validationQuery=SELECT 1 from dual
druid.testWhileIdle=true
druid.testOnBorrow=false
druid.testOnReturn=false
druid.poolPreparedStatements=true
druid.maxPoolPreparedStatementPerConnectionSize=20
druid.filters=stat,log4j
druid.connectionProperties=druid.stat.logSlowSql=true
#其他数据库
druid.postgress.validationQuery=SELECT 1
druid.mysql.validationQuery=SELECT 1