benma666:
  # 调试模式
  debug: true
  # websoket是否启用
  web-socket-enabled: true
  # 可以是springboot的bean名称（从容器中获取）或者具体的完整类路径（反射实例化，springboot的注解不会生效）
  ljq-default: DzDefaultLjq
  # 授权模式，cllx（精确到处理类型），sjdx（只要相关数据对象有授权就可以使用其下所有方法），默认为cllx
  xtqx-sqms: cllx
  # 配置的字典类别列表
  config-list: SYS_COMMON_APPCONFIG,SYS_MYSERVICE_APPCONFIG,SYS_SJGL_APPCONFIG
  # 密码解密密码
  fwq-ejmm: xxx
  # 密码解密密码
  sjzt-ejmm: xxx
  # 用户目前采用md5加密不需要设置密码
  yhxx-ejmm: xxx
  # 密码解密密码
  app-ejmm: xxx
  # 应用代码，没有应用都要独立的应用代码，与应用管理中的代码一致
  app-dm: sjsj
  #  datasource:
  #    kettle_default:
  #      ljc: jdbc:mysql://xxx:3306/xxxx?useOldAliasMetadataBehavior=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
  #      yhm: root
  #      mm: xxx
  #      lx: mysql
  #      kzxx-obj:
  #        kettleConfig:
  #          kuser: admin
  #          kpass: admin
  login:
    default-login: true
    # 登录失败次数
    dlsbcs: 5
    # 请求并发限制
    qqbfxz: 10
    # 用户同时在线会话数限制
    tszxhhsxz: 20
    # ip限制
#    ipxz: (123.147.251.132|123.147.249.154|27.11.159.27)
  service:
    # 统一代理地址，应用管理中统一代理的应用都只配置了项目名称，需要读取该配置补充为完整的地址
    tydlzd: http://localhost:9002
    addr: /index
    # 允许上传的文件类型
    yxscwjlx: xls,xlsx,txt,csv,zip,rar,7z,png,jpg,json,xml,pdf,doc,docx,ppt,pptx,mp3,mp4,ofd
    # 系统根目录
    xtgml: /benma666
  data:
    # 系统主密码
    password: xxx
    # sm2私钥
    private-key: xxx
    # sm2公钥
    public-key: xxx
  # 智能交换
  znjh:
    # 自动穿透调用，默认true
    zdctdy: true
    # 穿透调用等待时长
    ctdydd: 120000
    # 默认地址
    url: /default
    # 默认用户,专用同步账号
    user: "sys"
    # 应用初始化启动（非xxl场景支持），目前建议优先采用xxl调度，方便管理。
    app-init-start: false
    #线程池配置
    thread-pool:
      #核心线程数
      core-pool-size: 5
      #最大线程数
      max-pool-size: 5
      #队列大小 缓存多少个任务
      queue-capacity: 20000
      #线程活跃时间
      keep-alive-seconds: 600
  # kettle管理系统
  km:
    # 应用初始化启动
    app-init-start: true

server:
  # 服务器的HTTP端口，默认为8080
  port: 8090
  servlet:
    # 应用的访问路径
    context-path: "/sjsj-ht"
    session:
      # 重启会话保持
      persistent: true
      #单位(s)  这里是24小时
#      timeout: 24h
      timeout: 30m
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值25
      min-spare: 30
#    connection-timeout:
#    keep-alive-timeout:

spring:
  application:
    name: 数据世界
  security:
    user:
      name: jingma
      # spring权限框架密码
      password: jingma
      roles:
        - admin
  profiles:
    #active: oracle
    active: mysql
    include:
      - private
      - xxljob
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n.message
    encoding: UTF-8
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  100MB
      # 设置总上传的文件大小
      max-request-size:  100MB
      # 上传临时目录
      location: ${benma666.service.xtgml}/upload/tmp
      # 文件大小达到该阈值，将写入临时目录，默认为0，即所有文件都会直接写入磁盘临时文件中。
      file-size-threshold: 0B
      # 是否惰性处理请求，默认为false。
      resolveLazily: true
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:mydb
    username: sjsj2
    password: sjsj
    dbtype: oracle
#    url: jdbc:mysql://127.0.0.1:3307/sjsj2?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
#    username: sjsj2
#    password: sjsj
#    dbtype: mysql
    druid:
      name: default
      # 初始连接数
      initial-size: 2
      # 最小连接池数量
      min-idle: 2
      # 最大连接池数量
      max-active: 50
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒，必须小于keepAliveBetweenTimeMillis
      time-between-eviction-runs-millis: 600000
      # 配置一个连接在池中最小空闲的时间，达到此空闲时限时，超出最小空闲连接数的连接会被回收，单位是毫秒
      min-evictable-idle-time-millis: 60000
      # 配置一个连接在池中最大空闲的时间，超过此空闲时间，即使在最小空闲连接数范围内也会被回收，单位是毫秒
      max-evictable-idle-time-millis: 6000000
      # 连接超时
      socket-timeout: 600000
      # 这样每个物理连接在创建超过设定时间之后，也会被DestroyTask 强制回收掉，然后再创建新的物理连接。
      phy-timeout-millis: 18000000
      # 配置检测连接是否有效
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 连接池中的minIdle数量以内的连接，空闲时间超过minEvictableIdleTimeMillis，则会执行keepAlive操作，调用测试语句访问数据库，从而缩短连接的空闲时间，若测试不可用则会释放连接。
      keep-alive: true
      # 保活操作间隔
      keep-alive-between-time-millis: 1200000
      # 针对被应用获取的连接，超过时限未归还的连接会被强制回收，针对泄露连接的场景，获取连接一直没有释放，从实现看，执行sql中的连接不会被回收，执行频率与destroyTask一致，打开此配置可以在druid的web界面查看被获取连接的堆栈。
      remove-abandoned: true
      log-abandoned: true
      # 单位是秒
      remove-abandoned-timeout: 1800
      # 设置PSCache值，pool-prepared-statements这个参数基本没啥用，只要当前参数大于0就会设置pool-prepared-statements为true
      max-pool-prepared-statement-per-connection-size: 0
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: false
      # 异步初始化策略,必须要remove-abandoned为false才能生效，这样连接出问题的时候，每隔time-between-connect-error-millis秒请求，默认false，设置为true会单独启动一个定时任务创建重连链接
      #      async-init: false
      # 数据库服务宕机自动重连机制，从源码看设置为true重试达到connection-error-retry-attempts次后会停止重试，设置为false则会间隔timeBetweenConnectErrorMillis一直重试，默认false
      break-after-acquire-failure: false
      # 连接出错后再尝试连接
      connection-error-retry-attempts: 3
      # 连接出错后重试时间间隔
      time-between-connect-error-millis: 300000
      # 配置事务超时时间，单位秒
#      transaction-query-timeout: 6000
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: jingma
        # durid管理页面密码
        login-password: jingma
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 20000
          merge-sql: true
        wall:
          # 开发和测试环境true，正式环境false
          enabled: true
          config:
            multi-statement-allow: false
        slf4j:
          #打开日志
          enabled: true
          #关闭合并参数的sql
          statement-executable-sql-log-enable: true
          #关闭创建sql日志
          statement-create-after-log-enabled: false
          #sql预编译后
          statement-prepare-after-log-enabled: false
          #关闭参数
          statement-parameter-set-log-enabled: false
          statement-parameter-clear-log-enable: false
          #执行后
          statement-execute-after-log-enabled: false
          #关闭后
          statement-close-after-log-enabled: false
          #执行后，含有执行耗时
          statement-execute-batch-after-log-enabled: false
          statement-execute-query-after-log-enabled: false
          statement-execute-update-after-log-enabled: false
  # redis相关配置
  redis:
    # 是否使用redis
    enabled: true
    # 地址
    host: 192.168.1.22
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 5
    # 密码
    password:
    # 连接超时时间
    timeout: 30s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# actuator 监控配置
management:
  #actuator端口 如果不配置做默认使用上面8080端口
#  server:
#    port: 8090
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        #默认值访问health,info端点  用*可以包含全部端点
        include: "*"
      #修改访问路径 2.0之前默认是/; 2.0默认是/actuator可以通过这个属性值修改
      base-path: /actuator
  endpoint:
    shutdown:
      enabled: true #打开shutdown端点
    health:
      show-details: always #获得健康检查中所有指标的详细信息

# 日志配置
logging:
  #pattern: "%d{MM-dd HH:mm:ss} %-5level [%t] %logger{30}.%M:%L - %msg%n"
  #pattern-db: "{'scff':'%M','sch':'%L','message':'%m','threadName':'%t','level':'%level','ssxm':'%cn','loggerName':'%logger{30}','cjsj':'%date{yyyyMMddHHmmss}','gxsj':'%date{yyyyMMddHHmmss}'}"
  file:
    # 日志文件根目录
    path: ${benma666.service.xtgml}/logs
  level:
    root: info
    cn.benma666: trace
    org.springframework.core: debug
    org.springframework.boot: info
    druid.sql.Statement: debug
    # word模板引擎相关日志
    com.deepoove.poi: debug
  logback:
    console:
      level: debug
    #mylog:
      #level: ERROR
      #insert-sql: insert into SYS_LOG_HTRZ(id,cjsj,gxsj,xc,jb,scl,scff,sch,xx,ssxm) values(#{id},#{cjsj},#{gxsj},#{threadName},#{level},#{loggerName},#{scff},#{sch},#{message},#{ssxm})
#    rollingpolicy:
#      max-file-size: 20MB

#线程池配置
thread-pool:
  # 是否启用
  enabled: true
  #核心线程数
  core-pool-size: 10
  #最大线程数
  max-pool-size: 50
  #队列大小 缓存多少个任务
  queue-capacity: 20000
  #线程活跃时间
  keep-alive-seconds: 600
  #线程名字 前缀
  thread-name-prefix: myThread
# 微信相关
wx:
  # 微信接口基础地址
  api-base-url: https://api.weixin.qq.com
  # 微信登录接口参数
  api-login-params:
    # 奔马数据
    bmsj: appid=xxx&secret=xxx&grant_type=authorization_code&js_code=
    # 奔马数科
    bmsk: appid=xxx&secret=xxx&grant_type=authorization_code&js_code=
