/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.1.0

Source Server         : mydb
Source Server Version : 110200
Source Host           : 127.0.0.1:1521
Source Schema         : SJSJ

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2019-03-06 19:34:26
*/


-- ----------------------------
-- Table structure for SYS_FILE_RECORD
-- ----------------------------
DROP TABLE "SJSJ"."SYS_FILE_RECORD";
CREATE TABLE "SJSJ"."SYS_FILE_RECORD" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CREATEDATE" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"ETLDATE" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"ISDEL" VARCHAR2(10 BYTE) DEFAULT '0'  NULL ,
"YWDM" VARCHAR2(100 BYTE) NULL ,
"GLID" VARCHAR2(32 BYTE) NULL ,
"WJM" VARCHAR2(500 BYTE) NULL ,
"QCM" VARCHAR2(100 BYTE) NULL ,
"SCLB" VARCHAR2(10 BYTE) NULL ,
"SCLJ" VARCHAR2(1000 BYTE) NULL ,
"WJLX" VARCHAR2(10 BYTE) NULL ,
"WJLB" VARCHAR2(100 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_FILE_RECORD" IS '系统-文件-记录';
COMMENT ON COLUMN "SJSJ"."SYS_FILE_RECORD"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_FILE_RECORD"."CREATEDATE" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_FILE_RECORD"."ETLDATE" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_FILE_RECORD"."ISDEL" IS '删除标记';
COMMENT ON COLUMN "SJSJ"."SYS_FILE_RECORD"."YWDM" IS '业务代码;ZDRY_RYGL';
COMMENT ON COLUMN "SJSJ"."SYS_FILE_RECORD"."GLID" IS '关联id;前端传';
COMMENT ON COLUMN "SJSJ"."SYS_FILE_RECORD"."WJM" IS '文件名';
COMMENT ON COLUMN "SJSJ"."SYS_FILE_RECORD"."QCM" IS '去重码';
COMMENT ON COLUMN "SJSJ"."SYS_FILE_RECORD"."SCLB" IS '上传类别;LOCAL,FASTDFS';
COMMENT ON COLUMN "SJSJ"."SYS_FILE_RECORD"."SCLJ" IS '上传路径;ZDRY_RYGL/去重码.wjlx';
COMMENT ON COLUMN "SJSJ"."SYS_FILE_RECORD"."WJLX" IS '文件类型';
COMMENT ON COLUMN "SJSJ"."SYS_FILE_RECORD"."WJLB" IS '文件类别';

-- ----------------------------
-- Table structure for SYS_LOG_FWZR
-- ----------------------------
DROP TABLE "SJSJ"."SYS_LOG_FWZR";
CREATE TABLE "SJSJ"."SYS_LOG_FWZR" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"SJDX" VARCHAR2(32 BYTE) NULL ,
"CZIP" VARCHAR2(32 BYTE) NULL ,
"CZLX" VARCHAR2(32 BYTE) NULL ,
"URL" VARCHAR2(4000 BYTE) NULL ,
"XGCS" VARCHAR2(4000 BYTE) NULL ,
"TOKEN" VARCHAR2(32 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_LOG_FWZR" IS '系统-日志-访问日志';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."SJDX" IS '数据对象';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."CZIP" IS '操作ip';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."CZLX" IS '操作类型';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."URL" IS 'URL';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."XGCS" IS '相关参数';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."TOKEN" IS '权限id';

-- ----------------------------
-- Table structure for SYS_LOG_HTRZ
-- ----------------------------
DROP TABLE "SJSJ"."SYS_LOG_HTRZ";
CREATE TABLE "SJSJ"."SYS_LOG_HTRZ" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"XC" VARCHAR2(512 BYTE) NULL ,
"JB" VARCHAR2(512 BYTE) NULL ,
"SCL" VARCHAR2(512 BYTE) NULL ,
"SCH" VARCHAR2(8 BYTE) NULL ,
"XX" VARCHAR2(4000 BYTE) NULL ,
"SSXM" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_LOG_HTRZ" IS '系统-日志-后台日志';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_HTRZ"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_HTRZ"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_HTRZ"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_HTRZ"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_HTRZ"."XC" IS '线程';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_HTRZ"."JB" IS '级别';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_HTRZ"."SCL" IS '输出类';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_HTRZ"."SCH" IS '输出行';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_HTRZ"."XX" IS '消息';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_HTRZ"."SSXM" IS '所属项目';

-- ----------------------------
-- Table structure for SYS_QX_APP
-- ----------------------------
DROP TABLE "SJSJ"."SYS_QX_APP";
CREATE TABLE "SJSJ"."SYS_QX_APP" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"DM" VARCHAR2(32 BYTE) NULL ,
"MC" VARCHAR2(128 BYTE) NULL ,
"MS" VARCHAR2(4000 BYTE) NULL ,
"JP" VARCHAR2(512 BYTE) NULL ,
"QP" VARCHAR2(512 BYTE) NULL ,
"SJY" VARCHAR2(32 BYTE) NULL ,
"LB" VARCHAR2(512 BYTE) NULL ,
"BB" VARCHAR2(32 BYTE) NULL ,
"DZ" VARCHAR2(512 BYTE) NULL ,
"ZT" VARCHAR2(32 BYTE) NULL ,
"MM" VARCHAR2(32 BYTE) NULL ,
"ZDDLMS" VARCHAR2(32 BYTE) NULL ,
"JCGJZ" VARCHAR2(32 BYTE) NULL ,
"FWDK" VARCHAR2(32 BYTE) NULL ,
"TZDK" VARCHAR2(32 BYTE) NULL ,
"FWQ" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_QX_APP" IS '系统-权限-应用';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."DM" IS '代码;代表唯一数据对象，多处使用，唯一';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."MC" IS '名称';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."MS" IS '描述';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."JP" IS '简拼';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."QP" IS '全拼';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."SJY" IS '数据源';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."LB" IS '类别@SYS_QX_APPLB';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."BB" IS '版本';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."DZ" IS '地址';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."ZT" IS '状态@SYS_COMMON_ZT';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."MM" IS '密码';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."ZDDLMS" IS '自动登陆模式';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."JCGJZ" IS '监测关键字';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."FWDK" IS '访问端口';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."TZDK" IS '停止端口';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."FWQ" IS '服务器@SYS_QX_FWQ';

-- ----------------------------
-- Table structure for SYS_QX_FWQ
-- ----------------------------
DROP TABLE "SJSJ"."SYS_QX_FWQ";
CREATE TABLE "SJSJ"."SYS_QX_FWQ" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"IP" VARCHAR2(32 BYTE) NULL ,
"MS" VARCHAR2(1024 BYTE) NULL ,
"LB" VARCHAR2(32 BYTE) NULL ,
"MC" VARCHAR2(32 BYTE) NULL ,
"LX" VARCHAR2(32 BYTE) NULL ,
"MM" VARCHAR2(32 BYTE) NULL ,
"FZR" VARCHAR2(1024 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_QX_FWQ" IS '系统-权限-服务器';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."IP" IS 'IP';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."MS" IS '描述';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."LB" IS '类别@SYS_QX_FWQLB';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."MC" IS '名称';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."LX" IS '类型@SYS_QX_FWQLX;win、linux';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."MM" IS '密码';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."FZR" IS '负责人';

-- ----------------------------
-- Table structure for SYS_QX_JGXX
-- ----------------------------
DROP TABLE "SJSJ"."SYS_QX_JGXX";
CREATE TABLE "SJSJ"."SYS_QX_JGXX" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"JGDM" VARCHAR2(32 BYTE) NULL ,
"JGMC" VARCHAR2(256 BYTE) NULL ,
"MCJP" VARCHAR2(128 BYTE) NULL ,
"JGBM" VARCHAR2(256 BYTE) NULL ,
"JGJC" VARCHAR2(256 BYTE) NULL ,
"JCJP" VARCHAR2(128 BYTE) NULL ,
"JGLX" VARCHAR2(3 BYTE) NULL ,
"SJJG" VARCHAR2(32 BYTE) NULL ,
"JGCJ" NUMBER NULL ,
"LXR" VARCHAR2(128 BYTE) NULL ,
"LXRDH" VARCHAR2(128 BYTE) NULL ,
"JGYX" VARCHAR2(32 BYTE) NULL ,
"JGDZ" VARCHAR2(256 BYTE) NULL ,
"JGMS" VARCHAR2(512 BYTE) NULL ,
"BZ" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_QX_JGXX" IS '系统-权限-机构信息';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."JGDM" IS '机构代码';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."JGMC" IS '机构名称';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."MCJP" IS '名称简拼';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."JGBM" IS '机构别名';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."JGJC" IS '机构简称';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."JCJP" IS '简称简拼';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."JGLX" IS '机构类型';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."SJJG" IS '上级机构';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."JGCJ" IS '机构层级';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."LXR" IS '联系人';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."LXRDH" IS '联系人电话';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."JGYX" IS '机构邮箱';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."JGDZ" IS '机构地址';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."JGMS" IS '机构描述';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."BZ" IS '备注';

-- ----------------------------
-- Table structure for SYS_QX_YHXX
-- ----------------------------
DROP TABLE "SJSJ"."SYS_QX_YHXX";
CREATE TABLE "SJSJ"."SYS_QX_YHXX" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"YHXM" VARCHAR2(32 BYTE) NULL ,
"YHDM" VARCHAR2(32 BYTE) NULL ,
"YHMM" VARCHAR2(64 BYTE) NULL ,
"SFZH" VARCHAR2(18 BYTE) NULL ,
"YXQKS" VARCHAR2(8 BYTE) NULL ,
"YXQJS" VARCHAR2(8 BYTE) NULL ,
"SSJG" VARCHAR2(32 BYTE) NULL ,
"THLX" VARCHAR2(2 BYTE) NULL ,
"YHDJ" VARCHAR2(2 BYTE) NULL ,
"YHMS" VARCHAR2(1024 BYTE) NULL ,
"YHYX" VARCHAR2(32 BYTE) NULL ,
"LXDH" VARCHAR2(32 BYTE) NULL ,
"LXDZ" VARCHAR2(256 BYTE) NULL ,
"MZ" VARCHAR2(2 BYTE) NULL ,
"GJ" VARCHAR2(5 BYTE) NULL ,
"XL" VARCHAR2(2 BYTE) NULL ,
"ZZMM" VARCHAR2(2 BYTE) NULL ,
"ZW" VARCHAR2(2 BYTE) NULL ,
"ZJ" VARCHAR2(2 BYTE) NULL ,
"BZ" VARCHAR2(1024 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_QX_YHXX" IS '系统-权限-用户信息';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."YHXM" IS '用户姓名';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."YHDM" IS '用户代码';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."YHMM" IS '用户密码';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."SFZH" IS '身份证号';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."YXQKS" IS '有效期开始';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."YXQJS" IS '有效期结束';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."SSJG" IS '所属机构@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."THLX" IS '用户类型@SYS_QX_YHLX';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."YHDJ" IS '用户等级@SYS_QX_YHDJ';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."YHMS" IS '用户描述';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."YHYX" IS '用户邮箱';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."LXDH" IS '联系电话';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."LXDZ" IS '联系地址';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."MZ" IS '民族@SYS_COMMON_MZ';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."GJ" IS '国籍@SYS_COMMON_GJ';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."XL" IS '学历@SYS_COMMON_XL';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."ZZMM" IS '政治面貌@SYS_COMMON_ZZMM';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."ZW" IS '职务@SYS_QX_ZW';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."ZJ" IS '职级@SYS_QX_ZJ';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."BZ" IS '备注';

-- ----------------------------
-- Table structure for SYS_SJGL_SJDX
-- ----------------------------
DROP TABLE "SJSJ"."SYS_SJGL_SJDX";
CREATE TABLE "SJSJ"."SYS_SJGL_SJDX" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"DXDM" VARCHAR2(256 BYTE) NULL ,
"DXMC" VARCHAR2(256 BYTE) NULL ,
"DXMS" VARCHAR2(4000 BYTE) NULL ,
"DXJP" VARCHAR2(512 BYTE) NULL ,
"DXQP" VARCHAR2(512 BYTE) NULL ,
"DXLB" VARCHAR2(512 BYTE) NULL ,
"DXLX" VARCHAR2(32 BYTE) NULL ,
"DXZY" VARCHAR2(512 BYTE) NULL ,
"DXZTLX" VARCHAR2(32 BYTE) NULL ,
"DXZT" VARCHAR2(32 BYTE) DEFAULT 'default'  NULL ,
"DXGS" VARCHAR2(512 BYTE) NULL ,
"JTDX" VARCHAR2(64 BYTE) NULL ,
"ZJZD" VARCHAR2(32 BYTE) NULL ,
"QXZD" VARCHAR2(32 BYTE) NULL ,
"ZLZD" VARCHAR2(32 BYTE) NULL ,
"QCZD" VARCHAR2(32 BYTE) NULL ,
"JYZD" VARCHAR2(32 BYTE) NULL ,
"PCZD" VARCHAR2(32 BYTE) NULL ,
"YXXZD" VARCHAR2(32 BYTE) NULL ,
"FYTJXS" VARCHAR2(32 BYTE) DEFAULT '1'  NULL ,
"MRPX" VARCHAR2(256 BYTE) NULL ,
"CSCX" VARCHAR2(32 BYTE) DEFAULT '1'  NULL ,
"XQAN" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"CXTJ" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"SXXZ" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"LBFXK" VARCHAR2(8 BYTE) DEFAULT '0'  NULL ,
"BJXH" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"LJQ" VARCHAR2(512 BYTE) DEFAULT ''  NULL ,
"ZDDRSQL" CLOB NULL ,
"SQLMB" CLOB NULL ,
"CXLBKZ" CLOB NULL ,
"BJYMKZ" CLOB NULL ,
"PLYMKZ" CLOB NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_SJGL_SJDX" IS '系统-数据管理-数据对象';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."DXDM" IS '对象代码;代表唯一数据对象，多处使用，唯一';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."DXMC" IS '对象名称';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."DXMS" IS '对象描述';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."DXJP" IS '对象简拼';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."DXQP" IS '对象全拼';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."DXLB" IS '对象类别@SYS_SJGL_DXLB;标准对象、临时对象、系统对象等人工分类';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."DXLX" IS '对象类型@SYS_SJGL_DXLX;表、视图、excel、txt等';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."DXZY" IS '对象作用@SYS_SJGL_DXZY;增量导出、数据插入、数据更新、页面查询、页面新增、页面修改等';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."DXZTLX" IS '对象载体类型@SYS_SJGL_DXZTLX;ORACLE、POSTGRESS、MYSQL、GREEPLAM、本地文件、FTP文件、FASTDFS文件、SOLR、ES、HIVE、HBASE等';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."DXZT" IS '对象载体;根据对象载体类型不同，表示不同的具体载体，如具体数据库、ftp等';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."DXGS" IS '对象归属;数据库的某个用户、ftp的目录等';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."JTDX" IS '具体对象;数据库的表视图、文件名、文件正则等';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."ZJZD" IS '主键字段;用于查询详情等';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."QXZD" IS '权限字段;进行权限控制';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."ZLZD" IS '增量字段;进行增量抽取等';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."QCZD" IS '去重字段;用于插入更新';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."JYZD" IS '校验字段;用于存放校验信息';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."PCZD" IS '批次字段;用于存放批次号，知道具体数据来自哪次抽取等';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."YXXZD" IS '有效性字段;做逻辑删除等';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."FYTJXS" IS '分页统计形式@SYS_SJGL_FYTJXS;控制分页查询数据量统计形式，如：默认形式、异步统计、默认不统计';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."MRPX" IS '默认排序;查询时的默认排序规则';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."CSCX" IS '初始查询@SYS_COMMON_LJPD;控制查询页面是否初始化查询';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."XQAN" IS '详情按钮@SYS_COMMON_LJPD;控制是否展示';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."CXTJ" IS '查询条件@SYS_COMMON_LJPD;控制是否展示';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."SXXZ" IS '属性选择@SYS_COMMON_LJPD;控制是否展示';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."LBFXK" IS '列表复选框@SYS_COMMON_LJPD;控制是否展示';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."BJXH" IS '编辑序号@SYS_COMMON_LJPD;控制是否显示编辑页面的字段序号';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."LJQ" IS '拦截器;后台扩展系统';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."ZDDRSQL" IS '字段导入SQL;用于刷新对象字段';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."SQLMB" IS 'SQL模板;用于扩展后端，基于beetl实现';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."CXLBKZ" IS '查询列表扩展;可以扩展成各种基于数据查询的展示页面。';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."BJYMKZ" IS '编辑页面扩展;涵盖新增、修改、详情';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."PLYMKZ" IS '批量页面扩展;主要用于扩展批量上传页面';

-- ----------------------------
-- Table structure for SYS_SJGL_SJZD
-- ----------------------------
DROP TABLE "SJSJ"."SYS_SJGL_SJZD";
CREATE TABLE "SJSJ"."SYS_SJGL_SJZD" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"SJDX" VARCHAR2(32 BYTE) NULL ,
"ZDDM" VARCHAR2(32 BYTE) NULL ,
"ZDMC" VARCHAR2(128 BYTE) NULL ,
"ZDMS" VARCHAR2(256 BYTE) NULL ,
"ZDJP" VARCHAR2(256 BYTE) NULL ,
"ZDQP" VARCHAR2(1024 BYTE) NULL ,
"ZDLX" VARCHAR2(32 BYTE) NULL ,
"ZDCD" NUMBER NULL ,
"ZDKD" NUMBER DEFAULT 80  NULL ,
"ZDGD" NUMBER NULL ,
"CXMRZ" VARCHAR2(64 BYTE) NULL ,
"XZMRZ" VARCHAR2(64 BYTE) NULL ,
"KJLX" VARCHAR2(32 BYTE) DEFAULT 'input'  NULL ,
"ZDDX" VARCHAR2(32 BYTE) DEFAULT '0'  NULL ,
"ZDFY" VARCHAR2(32 BYTE) DEFAULT '0'  NULL ,
"YXPX" VARCHAR2(8 BYTE) DEFAULT '0'  NULL ,
"LBZS" VARCHAR2(8 BYTE) DEFAULT '0'  NULL ,
"CXZS" VARCHAR2(8 BYTE) DEFAULT '0'  NULL ,
"XZZS" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"BJZS" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"XQZS" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"CXBT" VARCHAR2(8 BYTE) DEFAULT '0'  NULL ,
"BJBT" VARCHAR2(8 BYTE) DEFAULT '0'  NULL ,
"YXBJ" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"ZDZDLB" VARCHAR2(32 BYTE) NULL ,
"ZDYWLB" VARCHAR2(32 BYTE) NULL ,
"GSHFF" VARCHAR2(64 BYTE) NULL ,
"FGSHFF" VARCHAR2(64 BYTE) NULL ,
"SZHD" VARCHAR2(64 BYTE) NULL ,
"ZDTS" VARCHAR2(256 BYTE) NULL ,
"HDYZGZ" VARCHAR2(256 BYTE) NULL ,
"QDYZGZ" VARCHAR2(256 BYTE) NULL ,
"STYLE" VARCHAR2(256 BYTE) NULL ,
"CSSL" VARCHAR2(128 BYTE) NULL ,
"QCBH" NUMBER NULL ,
"BZZD" VARCHAR2(32 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_SJGL_SJZD" IS '系统-数据管理-数据字段';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."SJDX" IS '数据对象';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDDM" IS '字段代码';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDMC" IS '字段名称';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDMS" IS '字段描述';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDJP" IS '字段简拼';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDQP" IS '字段全拼';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDLX" IS '字段类型';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDCD" IS '字段长度';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDKD" IS '字段宽度';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDGD" IS '字段高度';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."CXMRZ" IS '查询默认值';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."XZMRZ" IS '新增默认值';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."KJLX" IS '控件类型@SYS_SJGL_KJLX;默认为1，1就是输入框，2是时间框，3是下拉框；';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDDX" IS '字典多选@SYS_COMMON_LJPD;字典下拉框是否支持多选';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDFY" IS '字典分页@SYS_COMMON_LJPD;字典下拉框是否分页展示';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."YXPX" IS '允许排序@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."LBZS" IS '列表展示@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."CXZS" IS '查询展示@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."XZZS" IS '新增展示@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."BJZS" IS '编辑展示@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."XQZS" IS '详情展示@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."CXBT" IS '查询必填@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."BJBT" IS '编辑必填@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."YXBJ" IS '允许编辑@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDZDLB" IS '字段字典类别@SYS_COMMON_ZDLB';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDYWLB" IS '字典业务类别@SYS_SJGL_ZDYWLB';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."GSHFF" IS '格式化方法;方法名称，传入参数：数据、字段描述对象、行数据';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."FGSHFF" IS '反格式化方法;方法名称，传入参数：数据、字段描述对象、行数据';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."SZHD" IS '设值回调;设置值的回调方法';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDTS" IS '字段提示';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."HDYZGZ" IS '后端验证规则;人工输入';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."QDYZGZ" IS '前端验证规则;人工输入';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."STYLE" IS '前端样式;人工输入';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."CSSL" IS 'CSS类;将填充到class中';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."QCBH" IS '去重编号';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."BZZD" IS '标准字段';

-- ----------------------------
-- Table structure for SYS_SJGL_SJZT
-- ----------------------------
DROP TABLE "SJSJ"."SYS_SJGL_SJZT";
CREATE TABLE "SJSJ"."SYS_SJGL_SJZT" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"DM" VARCHAR2(32 BYTE) NULL ,
"MC" VARCHAR2(128 BYTE) NULL ,
"MS" VARCHAR2(4000 BYTE) NULL ,
"JP" VARCHAR2(512 BYTE) NULL ,
"QP" VARCHAR2(512 BYTE) NULL ,
"LX" VARCHAR2(100 BYTE) NULL ,
"FWFS" VARCHAR2(100 BYTE) NULL ,
"JNDI" VARCHAR2(100 BYTE) NULL ,
"LJC" VARCHAR2(1000 BYTE) NULL ,
"YHM" VARCHAR2(100 BYTE) NULL ,
"MM" VARCHAR2(32 BYTE) NULL ,
"ZT" VARCHAR2(100 BYTE) DEFAULT '0'  NULL ,
"CSYJ" VARCHAR2(100 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_SJGL_SJZT" IS '系统-数据管理-数据载体';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."DM" IS '代码;代表唯一数据对象，多处使用，唯一';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."MC" IS '名称';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."MS" IS '描述';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."JP" IS '简拼';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."QP" IS '全拼';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."LX" IS '类型';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."FWFS" IS '访问方式';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."JNDI" IS 'JNDI名称';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."LJC" IS '连接串';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."YHM" IS '用户名';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."MM" IS '密码';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."ZT" IS '状态';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."CSYJ" IS '测试语句';

-- ----------------------------
-- Table structure for SYS_SJGL_YHZDY
-- ----------------------------
DROP TABLE "SJSJ"."SYS_SJGL_YHZDY";
CREATE TABLE "SJSJ"."SYS_SJGL_YHZDY" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWBM" VARCHAR2(32 BYTE) NULL ,
"SJDX" VARCHAR2(32 BYTE) NULL ,
"SJZD" VARCHAR2(32 BYTE) NULL ,
"MRZ" VARCHAR2(64 BYTE) NULL ,
"LBZS" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"CXZS" VARCHAR2(8 BYTE) DEFAULT '0'  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_SJGL_YHZDY" IS '系统-数据管理-用户自定义';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."CJRDWBM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."SJDX" IS '数据对象';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."SJZD" IS '数据字段';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."MRZ" IS '默认值';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."LBZS" IS '列表展示@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."CXZS" IS '查询展示@SYS_COMMON_LJPD';

-- ----------------------------
-- Table structure for SYS_XMGL_RWXX
-- ----------------------------
DROP TABLE "SJSJ"."SYS_XMGL_RWXX";
CREATE TABLE "SJSJ"."SYS_XMGL_RWXX" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"APP" VARCHAR2(32 BYTE) NULL ,
"RWMC" VARCHAR2(256 BYTE) NULL ,
"RWMS" CLOB NULL ,
"RWDJ" VARCHAR2(32 BYTE) NULL ,
"KSSJ" VARCHAR2(14 BYTE) NULL ,
"JSSJ" VARCHAR2(14 BYTE) NULL ,
"SJYQ" VARCHAR2(256 BYTE) NULL ,
"DQZT" VARCHAR2(32 BYTE) NULL ,
"FZR" VARCHAR2(32 BYTE) NULL ,
"KFRY" VARCHAR2(256 BYTE) NULL ,
"KHDJR" VARCHAR2(256 BYTE) NULL ,
"RWBZ" VARCHAR2(4000 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_XMGL_RWXX" IS '系统-项目管理-任务信息';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."APP" IS '应用@SYS_QX_APP';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."RWMC" IS '任务名称';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."RWMS" IS '任务描述';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."RWDJ" IS '任务等级@SYS_COMMON_DJ';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."KSSJ" IS '开始时间';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."JSSJ" IS '结束时间';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."SJYQ" IS '时间要求';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."DQZT" IS '当前状态';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."FZR" IS '负责人@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."KFRY" IS '开发人员@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."KHDJR" IS '客户对接人@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."RWBZ" IS '任务备注';

-- ----------------------------
-- Table structure for SYS_YXJK_JKRW
-- ----------------------------
DROP TABLE "SJSJ"."SYS_YXJK_JKRW";
CREATE TABLE "SJSJ"."SYS_YXJK_JKRW" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"RWLX" VARCHAR2(32 BYTE) NULL ,
"JTRW" VARCHAR2(32 BYTE) NULL ,
"LXRXM" VARCHAR2(64 BYTE) NULL ,
"LXRDM" VARCHAR2(32 BYTE) NULL ,
"LXDWMC" VARCHAR2(256 BYTE) NULL ,
"LXDWDM" VARCHAR2(32 BYTE) NULL ,
"YLRW" VARCHAR2(512 BYTE) NULL ,
"RWZT" VARCHAR2(32 BYTE) NULL ,
"RWDJ" VARCHAR2(32 BYTE) NULL ,
"CLFK" VARCHAR2(256 BYTE) NULL ,
"JCSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"XXMB" VARCHAR2(512 BYTE) NULL ,
"YCYY" VARCHAR2(4000 BYTE) NULL ,
"RWMC" VARCHAR2(256 BYTE) NULL ,
"RWLB" VARCHAR2(32 BYTE) NULL ,
"RWPCH" VARCHAR2(64 BYTE) NULL ,
"RWDM" VARCHAR2(64 BYTE) NULL ,
"RWDS" VARCHAR2(64 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_YXJK_JKRW" IS '系统-运行监控-监控任务';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."PX" IS '排序;按顺序监控';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."RWLX" IS '任务类型@SYS_YXJK_RWLX;监控任务的类型';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."JTRW" IS '具体任务';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."LXRXM" IS '联系人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."LXRDM" IS '联系人代码@SYS_COMMON_USER;可选，多选，会收到短信和工作平台消息';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."LXDWMC" IS '联系单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."LXDWDM" IS '联系单位代码@SYS_COMMON_ORG;可选，会收到短信和工作平台消息';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."YLRW" IS '依赖任务';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."RWZT" IS '任务状态@SYS_COMMON_ZT;最新';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."RWDJ" IS '任务等级@SYS_COMMON_DJ';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."CLFK" IS '处理反馈;人工反馈处理进度，生成消息，按异常消息渠道发送消息给相关联系人';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."JCSJ" IS '监测时间;最新一次进行数据库状态监测的时间';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."XXMB" IS '消息模板;监控到异常时根据此模板生成预警消息';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."YCYY" IS '异常原因;监控系统生成，实际异常信息，具体问题定位';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."RWMC" IS '任务名称';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."RWLB" IS '任务类别;人工业务上的分类';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."RWPCH" IS '任务批次号';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."RWDM" IS '任务代码';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."RWDS" IS '任务定时;为空表示持续执行';

-- ----------------------------
-- Table structure for SYS_YXJK_XX
-- ----------------------------
DROP TABLE "SJSJ"."SYS_YXJK_XX";
CREATE TABLE "SJSJ"."SYS_YXJK_XX" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"JKRW" VARCHAR2(32 BYTE) NULL ,
"XXLX" VARCHAR2(32 BYTE) NULL ,
"YCYY" VARCHAR2(4000 BYTE) NULL ,
"XXNR" VARCHAR2(256 BYTE) NULL ,
"XXDJ" VARCHAR2(32 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_YXJK_XX" IS '系统-运行监控-消息';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_XX"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_XX"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_XX"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_XX"."YXX" IS '有效性@SYS_COMMON_LJPD;无效的消息不发送';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_XX"."PX" IS '排序;按顺序监控';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_XX"."JKRW" IS '监控任务';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_XX"."XXLX" IS '消息类型@SYS_YXJK_XXLX;异常、恢复，跟进';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_XX"."YCYY" IS '异常原因;监控系统生成，实际异常信息，具体问题定位';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_XX"."XXNR" IS '消息内容;通过消息模板生成';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_XX"."XXDJ" IS '消息等级@SYS_COMMON_JJCD';

-- ----------------------------
-- Table structure for SYS_YXJK_ZDYSQL
-- ----------------------------
DROP TABLE "SJSJ"."SYS_YXJK_ZDYSQL";
CREATE TABLE "SJSJ"."SYS_YXJK_ZDYSQL" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"DM" VARCHAR2(32 BYTE) NULL ,
"MC" VARCHAR2(128 BYTE) NULL ,
"MS" VARCHAR2(4000 BYTE) NULL ,
"JP" VARCHAR2(512 BYTE) NULL ,
"QP" VARCHAR2(512 BYTE) NULL ,
"SQL" VARCHAR2(4000 BYTE) NULL ,
"ZT" VARCHAR2(32 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_YXJK_ZDYSQL" IS '系统-运行监控-自定义sql';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."DM" IS '代码;代表唯一数据对象，多处使用，唯一';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."MC" IS '名称';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."MS" IS '描述';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."JP" IS '简拼';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."QP" IS '全拼';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."SQL" IS '自定义sql';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."ZT" IS '状态@SYS_COMMON_ZT';

-- ----------------------------
-- Table structure for SYS_ZD_TYZD
-- ----------------------------
DROP TABLE "SJSJ"."SYS_ZD_TYZD";
CREATE TABLE "SJSJ"."SYS_ZD_TYZD" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"DM" VARCHAR2(100 BYTE) NULL ,
"MC" VARCHAR2(4000 BYTE) NULL ,
"MS" VARCHAR2(4000 BYTE) NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"JP" VARCHAR2(4000 BYTE) NULL ,
"QP" VARCHAR2(4000 BYTE) NULL ,
"ZDLB" VARCHAR2(100 BYTE) NULL ,
"BZZDLB" VARCHAR2(100 BYTE) NULL ,
"LBSQL" VARCHAR2(500 BYTE) NULL ,
"CREATEDATE" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"ETLDATE" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"SJLY" VARCHAR2(300 BYTE) NULL ,
"ISDEL" VARCHAR2(10 BYTE) DEFAULT '0'  NULL ,
"UPNODE" VARCHAR2(100 BYTE) NULL ,
"CACHE" VARCHAR2(10 BYTE) DEFAULT '1'  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_ZD_TYZD" IS '系统-字典-统一字典';
COMMENT ON COLUMN "SJSJ"."SYS_ZD_TYZD"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_ZD_TYZD"."DM" IS '代码';
COMMENT ON COLUMN "SJSJ"."SYS_ZD_TYZD"."MC" IS '名称';
COMMENT ON COLUMN "SJSJ"."SYS_ZD_TYZD"."MS" IS '描述';
COMMENT ON COLUMN "SJSJ"."SYS_ZD_TYZD"."PX" IS '排序;建议排序都按10、20、30的方式排序，方便修改穿插';
COMMENT ON COLUMN "SJSJ"."SYS_ZD_TYZD"."JP" IS '简拼';
COMMENT ON COLUMN "SJSJ"."SYS_ZD_TYZD"."QP" IS '全拼';
COMMENT ON COLUMN "SJSJ"."SYS_ZD_TYZD"."ZDLB" IS '字典类别';
COMMENT ON COLUMN "SJSJ"."SYS_ZD_TYZD"."BZZDLB" IS '标准字典类别;用于数据标准化等场景，如性别可以有几套字典，然后关联一个标准字典,进一步通过mc关联';
COMMENT ON COLUMN "SJSJ"."SYS_ZD_TYZD"."LBSQL" IS '类别SQL;当次SQL为空时，字典默认在此统一字典表中，有SQL则通过SQL获取字典';
COMMENT ON COLUMN "SJSJ"."SYS_ZD_TYZD"."CREATEDATE" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_ZD_TYZD"."ETLDATE" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_ZD_TYZD"."SJLY" IS '数据来源';
COMMENT ON COLUMN "SJSJ"."SYS_ZD_TYZD"."ISDEL" IS '是否删除;与共享平台一致，所以这里没有采用中文简拼命名';
COMMENT ON COLUMN "SJSJ"."SYS_ZD_TYZD"."UPNODE" IS '父节点';
COMMENT ON COLUMN "SJSJ"."SYS_ZD_TYZD"."CACHE" IS '是否缓存';

-- ----------------------------
-- Indexes structure for table SYS_FILE_RECORD
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_FILE_RECORD
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_FILE_RECORD" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_FILE_RECORD" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_FILE_RECORD" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_FILE_RECORD" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_FILE_RECORD
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_FILE_RECORD" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_LOG_FWZR
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_LOG_FWZR
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_LOG_FWZR" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_LOG_FWZR" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_LOG_FWZR
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_LOG_FWZR" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_LOG_HTRZ
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_LOG_HTRZ
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_LOG_HTRZ" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_LOG_HTRZ
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_LOG_HTRZ" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_QX_APP
-- ----------------------------
CREATE UNIQUE INDEX "SJSJ"."IDX_SYS_QX_APP_DM"
ON "SJSJ"."SYS_QX_APP" ("DM" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table SYS_QX_APP
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_APP" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_QX_APP
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_APP" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_QX_FWQ
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_QX_FWQ
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_FWQ" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_QX_FWQ
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_FWQ" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_QX_JGXX
-- ----------------------------
CREATE UNIQUE INDEX "SJSJ"."IDX_SYS_QX_JGXX_JGDM"
ON "SJSJ"."SYS_QX_JGXX" ("JGDM" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table SYS_QX_JGXX
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_JGXX" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_QX_JGXX" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_QX_JGXX
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_JGXX" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_QX_YHXX
-- ----------------------------
CREATE UNIQUE INDEX "SJSJ"."IDX_SYS_QX_YHXX_YHDM"
ON "SJSJ"."SYS_QX_YHXX" ("YHDM" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table SYS_QX_YHXX
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_YHXX" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_QX_YHXX" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_QX_YHXX
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_YHXX" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_SJGL_SJDX
-- ----------------------------
CREATE UNIQUE INDEX "SJSJ"."IDX_SYS_SJGL_SJDX"
ON "SJSJ"."SYS_SJGL_SJDX" ("DXDM" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table SYS_SJGL_SJDX
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_SJDX" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_SJGL_SJDX" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_SJGL_SJDX
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_SJDX" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_SJGL_SJZD
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_SJGL_SJZD
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_SJZD" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_SJGL_SJZD" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_SJGL_SJZD
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_SJZD" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_SJGL_SJZT
-- ----------------------------
CREATE UNIQUE INDEX "SJSJ"."IDX_SYS_SJGL_SJK_DM"
ON "SJSJ"."SYS_SJGL_SJZT" ("DM" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table SYS_SJGL_SJZT
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_SJZT" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_SJGL_SJZT
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_SJZT" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_SJGL_YHZDY
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_SJGL_YHZDY
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_YHZDY" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_SJGL_YHZDY" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_SJGL_YHZDY
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_YHZDY" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table SYS_XMGL_RWXX
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_XMGL_RWXX" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Indexes structure for table SYS_YXJK_JKRW
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_YXJK_JKRW
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_YXJK_JKRW" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_YXJK_JKRW
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_YXJK_JKRW" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_YXJK_XX
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_YXJK_XX
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_YXJK_XX" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_YXJK_XX
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_YXJK_XX" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table SYS_YXJK_ZDYSQL
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_YXJK_ZDYSQL" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Indexes structure for table SYS_ZD_TYZD
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_ZD_TYZD
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_ZD_TYZD" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_ZD_TYZD" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_ZD_TYZD
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_ZD_TYZD" ADD PRIMARY KEY ("ID");
