/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.1.0

Source Server         : mydb
Source Server Version : 110200
Source Host           : 127.0.0.1:1521
Source Schema         : SJSJ

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2020-02-14 10:44:41
*/


-- ----------------------------
-- Table structure for JCGA_JCYG_JCXX
-- ----------------------------
DROP TABLE "SJSJ"."JCGA_JCYG_JCXX";
CREATE TABLE "SJSJ"."JCGA_JCYG_JCXX" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"DW" VARCHAR2(128 BYTE) NULL ,
"DKWB" VARCHAR2(128 BYTE) DEFAULT '0'  NULL ,
"DKWBDWMC" VARCHAR2(128 BYTE) NULL ,
"BM" VARCHAR2(128 BYTE) NULL ,
"CDYHBW" VARCHAR2(128 BYTE) DEFAULT '0'  NULL ,
"GWGZ" VARCHAR2(128 BYTE) NULL ,
"GWJB" VARCHAR2(128 BYTE) NULL ,
"YGXM" VARCHAR2(128 BYTE) NULL ,
"XB" VARCHAR2(128 BYTE) NULL ,
"NL" VARCHAR2(128 BYTE) NULL ,
"CSRQ" VARCHAR2(128 BYTE) NULL ,
"ZJLX" VARCHAR2(128 BYTE) NULL ,
"GMSFHM" VARCHAR2(128 BYTE) NULL ,
"MZ" VARCHAR2(128 BYTE) NULL ,
"ZZMM" VARCHAR2(128 BYTE) NULL ,
"WHCD" VARCHAR2(128 BYTE) NULL ,
"JTDH" VARCHAR2(128 BYTE) NULL ,
"BGDH" VARCHAR2(128 BYTE) NULL ,
"SJ" VARCHAR2(128 BYTE) NULL ,
"JG" VARCHAR2(128 BYTE) NULL ,
"HJDZ" VARCHAR2(128 BYTE) NULL ,
"XZDZ" VARCHAR2(128 BYTE) NULL ,
"ZW" VARCHAR2(128 BYTE) NULL ,
"YGXZ" VARCHAR2(128 BYTE) NULL ,
"DBDWSJ" VARCHAR2(128 BYTE) NULL ,
"JSZC" VARCHAR2(128 BYTE) NULL ,
"ZYXKZMC" VARCHAR2(128 BYTE) NULL ,
"ZYXKZBH" VARCHAR2(128 BYTE) NULL ,
"QTTC" VARCHAR2(128 BYTE) NULL ,
"KZQTXZ" VARCHAR2(128 BYTE) DEFAULT '0'  NULL ,
"KZQTXZLX" VARCHAR2(128 BYTE) NULL ,
"YGBH" VARCHAR2(128 BYTE) NULL ,
"QQ" VARCHAR2(128 BYTE) NULL ,
"MSN" VARCHAR2(128 BYTE) NULL ,
"KSCJ" VARCHAR2(128 BYTE) NULL ,
"SBGLQTXZ" VARCHAR2(128 BYTE) DEFAULT '0'  NULL ,
"GLQTXZLX" VARCHAR2(128 BYTE) NULL ,
"GLQTXZYXQ" VARCHAR2(128 BYTE) NULL ,
"LZSJ" VARCHAR2(128 BYTE) NULL ,
"LZYY" VARCHAR2(1024 BYTE) NULL ,
"ZZZT" VARCHAR2(128 BYTE) DEFAULT '1'  NULL ,
"JNHBLJ" VARCHAR2(128 BYTE) NULL ,
"JNHBLJRYHQZRYJC" VARCHAR2(128 BYTE) NULL ,
"JQFRZZ" VARCHAR2(128 BYTE) NULL ,
"JQSFJJHGL" VARCHAR2(128 BYTE) NULL ,
"ZXYQFKZS" VARCHAR2(128 BYTE) NULL ,
"JSDYWQZ" VARCHAR2(128 BYTE) NULL ,
"RCJSCL" VARCHAR2(128 BYTE) NULL ,
"SFTZ" VARCHAR2(128 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."JCGA_JCYG_JCXX" IS '机场公安-机场用工-基础信息';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."DW" IS '单位';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."DKWB" IS '对口/外包';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."DKWBDWMC" IS '对口/外包单位名称';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."BM" IS '部门';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."CDYHBW" IS '重点要害部位';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."GWGZ" IS '岗位/工种';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."GWJB" IS '岗位级别';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."YGXM" IS '员工姓名';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."XB" IS '性别';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."NL" IS '年龄';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."CSRQ" IS '出生日期';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."ZJLX" IS '证件类型';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."GMSFHM" IS '公民身份号码';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."MZ" IS '民族';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."ZZMM" IS '政治面貌';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."WHCD" IS '文化程度';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."JTDH" IS '家庭电话';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."BGDH" IS '办公电话';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."SJ" IS '手机';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."JG" IS '籍贯';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."HJDZ" IS '户籍地址';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."XZDZ" IS '现住地址';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."ZW" IS '职务';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."YGXZ" IS '用工性质';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."DBDWSJ" IS '到本单位时间';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."JSZC" IS '技术职称';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."ZYXKZMC" IS '执业许可证名称';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."ZYXKZBH" IS '执业许可证编号';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."QTTC" IS '其他特长';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."KZQTXZ" IS '控制区通行证';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."KZQTXZLX" IS '控制区通行证类型';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."YGBH" IS '员工编号';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."QQ" IS 'QQ号码';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."MSN" IS 'MSN登录名';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."KSCJ" IS '考试成绩';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."SBGLQTXZ" IS '申办隔离区通行证件';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."GLQTXZLX" IS '隔离区通行证件类型';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."GLQTXZYXQ" IS '隔离区证件有效期';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."LZSJ" IS '离职时间';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."LZYY" IS '离职原因';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."ZZZT" IS '在职状态@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."JNHBLJ" IS '今年以来有无湖北旅居史@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."JNHBLJRYHQZRYJC" IS '今年以来是否与湖北旅居人员/确诊人员有密切接触@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."JQFRZZ" IS '近期是否有发热症状@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."JQSFJJHGL" IS '近期是否按规定落实居家或在医学地隔离观察@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."ZXYQFKZS" IS '是否知晓疫情防控知识@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."JSDYWQZ" IS '家属（包括但不限下列社会关系）中有无确诊人员@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."RCJSCL" IS '日常驾驶车辆车牌号码';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_JCXX"."SFTZ" IS '是否同住@SYS_COMMON_LJPD';

-- ----------------------------
-- Table structure for JCGA_JCYG_SHGX
-- ----------------------------
DROP TABLE "SJSJ"."JCGA_JCYG_SHGX";
CREATE TABLE "SJSJ"."JCGA_JCYG_SHGX" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"SHGX" VARCHAR2(32 BYTE) NULL ,
"XM" VARCHAR2(32 BYTE) NULL ,
"XB" VARCHAR2(32 BYTE) NULL ,
"ZJLX" VARCHAR2(32 BYTE) NULL ,
"ZJHM" VARCHAR2(32 BYTE) NULL ,
"XZDZ" VARCHAR2(128 BYTE) NULL ,
"LXDH" VARCHAR2(32 BYTE) NULL ,
"YGBH" VARCHAR2(128 BYTE) NULL ,
"BJHC" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"HJDZ" VARCHAR2(128 BYTE) NULL ,
"BZ" VARCHAR2(1280 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."JCGA_JCYG_SHGX" IS '机场公安-机场用工-社会关系';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_SHGX"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_SHGX"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_SHGX"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_SHGX"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_SHGX"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_SHGX"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_SHGX"."SHGX" IS '社会关系';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_SHGX"."XM" IS '姓名';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_SHGX"."XB" IS '性别';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_SHGX"."ZJLX" IS '证件类型';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_SHGX"."ZJHM" IS '身份号码';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_SHGX"."XZDZ" IS '现住地址';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_SHGX"."LXDH" IS '联系电话';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_SHGX"."YGBH" IS '员工编号';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_SHGX"."BJHC" IS '背景核查';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_SHGX"."HJDZ" IS '户籍地址';
COMMENT ON COLUMN "SJSJ"."JCGA_JCYG_SHGX"."BZ" IS '备注';

-- ----------------------------
-- Table structure for SYS_LOG_FWZR
-- ----------------------------
DROP TABLE "SJSJ"."SYS_LOG_FWZR";
CREATE TABLE "SJSJ"."SYS_LOG_FWZR" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"SJDX" VARCHAR2(32 BYTE) NULL ,
"CZIP" VARCHAR2(32 BYTE) NULL ,
"CZLX" VARCHAR2(32 BYTE) NULL ,
"URL" VARCHAR2(4000 BYTE) NULL ,
"XGCS" VARCHAR2(4000 BYTE) NULL ,
"TOKEN" VARCHAR2(32 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_LOG_FWZR" IS '系统-日志-访问日志';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."SJDX" IS '数据对象';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."CZIP" IS '操作ip';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."CZLX" IS '操作类型';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."URL" IS 'URL';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."XGCS" IS '相关参数';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_FWZR"."TOKEN" IS '权限id';

-- ----------------------------
-- Table structure for SYS_LOG_HTRZ
-- ----------------------------
DROP TABLE "SJSJ"."SYS_LOG_HTRZ";
CREATE TABLE "SJSJ"."SYS_LOG_HTRZ" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"XC" VARCHAR2(512 BYTE) NULL ,
"JB" VARCHAR2(512 BYTE) NULL ,
"SCL" VARCHAR2(512 BYTE) NULL ,
"SCH" VARCHAR2(8 BYTE) NULL ,
"XX" VARCHAR2(4000 BYTE) NULL ,
"SSXM" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_LOG_HTRZ" IS '系统-日志-后台日志';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_HTRZ"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_HTRZ"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_HTRZ"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_HTRZ"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_HTRZ"."XC" IS '线程';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_HTRZ"."JB" IS '级别';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_HTRZ"."SCL" IS '输出类';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_HTRZ"."SCH" IS '输出行';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_HTRZ"."XX" IS '消息';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_HTRZ"."SSXM" IS '所属项目';

-- ----------------------------
-- Table structure for SYS_LOG_SJLZRZ
-- ----------------------------
DROP TABLE "SJSJ"."SYS_LOG_SJLZRZ";
CREATE TABLE "SJSJ"."SYS_LOG_SJLZRZ" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"SJDX" VARCHAR2(32 BYTE) NULL ,
"SJZD" VARCHAR2(32 BYTE) NULL ,
"ZY" VARCHAR2(100 BYTE) NULL ,
"ZYMC" VARCHAR2(100 BYTE) NULL ,
"KSSJ" VARCHAR2(14 BYTE) NULL ,
"JSSJ" VARCHAR2(14 BYTE) NULL ,
"ZLSJC" VARCHAR2(100 BYTE) NULL ,
"JG" VARCHAR2(100 BYTE) NULL ,
"DQL" NUMBER DEFAULT 0  NULL ,
"XZL" NUMBER DEFAULT 0  NULL ,
"CFL" NUMBER DEFAULT 0  NULL ,
"WXL" NUMBER DEFAULT 0  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_LOG_SJLZRZ" IS '系统-日志-数据流转日志';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJLZRZ"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJLZRZ"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJLZRZ"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJLZRZ"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJLZRZ"."SJDX" IS '数据对象';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJLZRZ"."SJZD" IS '数据账单';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJLZRZ"."ZY" IS '作业';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJLZRZ"."ZYMC" IS '作业名称';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJLZRZ"."KSSJ" IS '开始时间';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJLZRZ"."JSSJ" IS '结束时间';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJLZRZ"."ZLSJC" IS '抽取标志';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJLZRZ"."JG" IS '结果';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJLZRZ"."DQL" IS '读取量';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJLZRZ"."XZL" IS '新增量';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJLZRZ"."CFL" IS '重复量';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJLZRZ"."WXL" IS '无效量';

-- ----------------------------
-- Table structure for SYS_LOG_SJSCCW
-- ----------------------------
DROP TABLE "SJSJ"."SYS_LOG_SJSCCW";
CREATE TABLE "SJSJ"."SYS_LOG_SJSCCW" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"SJDX" VARCHAR2(32 BYTE) NULL ,
"SJWJ" VARCHAR2(32 BYTE) NULL ,
"SJH" VARCHAR2(32 BYTE) NULL ,
"SJL" VARCHAR2(32 BYTE) NULL ,
"SJLM" VARCHAR2(128 BYTE) NULL ,
"SJZ" VARCHAR2(1024 BYTE) NULL ,
"CWXX" VARCHAR2(1024 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_LOG_SJSCCW" IS '系统-日志-数据上传错误';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJSCCW"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJSCCW"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJSCCW"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJSCCW"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJSCCW"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJSCCW"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJSCCW"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJSCCW"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJSCCW"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJSCCW"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJSCCW"."SJDX" IS '数据对象';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJSCCW"."SJWJ" IS '数据文件';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJSCCW"."SJH" IS '数据行';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJSCCW"."SJL" IS '数据列';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJSCCW"."SJLM" IS '数据列名';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJSCCW"."SJZ" IS '数据值';
COMMENT ON COLUMN "SJSJ"."SYS_LOG_SJSCCW"."CWXX" IS '错误信息';

-- ----------------------------
-- Table structure for SYS_PTGL_YJFK
-- ----------------------------
DROP TABLE "SJSJ"."SYS_PTGL_YJFK";
CREATE TABLE "SJSJ"."SYS_PTGL_YJFK" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"BT" VARCHAR2(256 BYTE) NULL ,
"SJDX" VARCHAR2(256 BYTE) NULL ,
"BQ" VARCHAR2(256 BYTE) NULL ,
"LX" VARCHAR2(256 BYTE) DEFAULT '02'  NULL ,
"NR" CLOB NULL ,
"JP" VARCHAR2(256 BYTE) NULL ,
"QP" VARCHAR2(1024 BYTE) NULL ,
"YDCS" NUMBER DEFAULT 0  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_PTGL_YJFK" IS '系统-平台管理-意见反馈';
COMMENT ON COLUMN "SJSJ"."SYS_PTGL_YJFK"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_PTGL_YJFK"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_PTGL_YJFK"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_PTGL_YJFK"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_PTGL_YJFK"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_PTGL_YJFK"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_PTGL_YJFK"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_PTGL_YJFK"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_PTGL_YJFK"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_PTGL_YJFK"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_PTGL_YJFK"."BT" IS '标题';
COMMENT ON COLUMN "SJSJ"."SYS_PTGL_YJFK"."SJDX" IS '功能板块@SYS_SJGL_SJDX';
COMMENT ON COLUMN "SJSJ"."SYS_PTGL_YJFK"."BQ" IS '标签';
COMMENT ON COLUMN "SJSJ"."SYS_PTGL_YJFK"."LX" IS '类型@SYS_PTGL_YJLX';
COMMENT ON COLUMN "SJSJ"."SYS_PTGL_YJFK"."NR" IS '内容';
COMMENT ON COLUMN "SJSJ"."SYS_PTGL_YJFK"."JP" IS '简拼';
COMMENT ON COLUMN "SJSJ"."SYS_PTGL_YJFK"."QP" IS '全拼';
COMMENT ON COLUMN "SJSJ"."SYS_PTGL_YJFK"."YDCS" IS '阅读次数';

-- ----------------------------
-- Table structure for SYS_QX_APP
-- ----------------------------
DROP TABLE "SJSJ"."SYS_QX_APP";
CREATE TABLE "SJSJ"."SYS_QX_APP" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"DM" VARCHAR2(32 BYTE) NULL ,
"MC" VARCHAR2(128 BYTE) NULL ,
"MS" VARCHAR2(4000 BYTE) NULL ,
"JP" VARCHAR2(512 BYTE) NULL ,
"QP" VARCHAR2(512 BYTE) NULL ,
"SJY" VARCHAR2(512 BYTE) NULL ,
"LB" VARCHAR2(512 BYTE) NULL ,
"BB" VARCHAR2(32 BYTE) NULL ,
"DZ" VARCHAR2(512 BYTE) NULL ,
"ZT" VARCHAR2(32 BYTE) NULL ,
"MM" VARCHAR2(32 BYTE) NULL ,
"ZDDLMS" VARCHAR2(32 BYTE) NULL ,
"JCGJZ" VARCHAR2(32 BYTE) NULL ,
"FWDK" VARCHAR2(32 BYTE) NULL ,
"TZDK" VARCHAR2(32 BYTE) NULL ,
"FWQ" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_QX_APP" IS '系统-权限-应用';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."DM" IS '代码;代表唯一数据对象，多处使用，唯一';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."MC" IS '名称';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."MS" IS '描述';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."JP" IS '简拼';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."QP" IS '全拼';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."SJY" IS '数据源';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."LB" IS '类别@SYS_QX_APPLB';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."BB" IS '版本';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."DZ" IS '地址';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."ZT" IS '状态@SYS_COMMON_ZT';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."MM" IS '密码';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."ZDDLMS" IS '自动登陆模式';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."JCGJZ" IS '监测关键字';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."FWDK" IS '访问端口';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."TZDK" IS '停止端口';
COMMENT ON COLUMN "SJSJ"."SYS_QX_APP"."FWQ" IS '服务器@SYS_QX_FWQ';

-- ----------------------------
-- Table structure for SYS_QX_FWQ
-- ----------------------------
DROP TABLE "SJSJ"."SYS_QX_FWQ";
CREATE TABLE "SJSJ"."SYS_QX_FWQ" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"IP" VARCHAR2(32 BYTE) NULL ,
"MS" VARCHAR2(1024 BYTE) NULL ,
"LB" VARCHAR2(32 BYTE) NULL ,
"MC" VARCHAR2(32 BYTE) NULL ,
"LX" VARCHAR2(32 BYTE) NULL ,
"MM" VARCHAR2(32 BYTE) NULL ,
"FZR" VARCHAR2(1024 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_QX_FWQ" IS '系统-权限-服务器';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."IP" IS 'IP';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."MS" IS '描述';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."LB" IS '类别@SYS_QX_FWQLB';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."MC" IS '名称';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."LX" IS '类型@SYS_QX_FWQLX;win、linux';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."MM" IS '密码';
COMMENT ON COLUMN "SJSJ"."SYS_QX_FWQ"."FZR" IS '负责人';

-- ----------------------------
-- Table structure for SYS_QX_JGXX
-- ----------------------------
DROP TABLE "SJSJ"."SYS_QX_JGXX";
CREATE TABLE "SJSJ"."SYS_QX_JGXX" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"JGDM" VARCHAR2(32 BYTE) NULL ,
"JGMC" VARCHAR2(256 BYTE) NULL ,
"MCJP" VARCHAR2(1024 BYTE) NULL ,
"JGBM" VARCHAR2(256 BYTE) NULL ,
"JGJC" VARCHAR2(256 BYTE) NULL ,
"JCJP" VARCHAR2(128 BYTE) NULL ,
"JGLX" VARCHAR2(3 BYTE) NULL ,
"SJJG" VARCHAR2(32 BYTE) NULL ,
"JGCJ" NUMBER NULL ,
"LXR" VARCHAR2(128 BYTE) NULL ,
"LXRDH" VARCHAR2(128 BYTE) NULL ,
"JGYX" VARCHAR2(32 BYTE) NULL ,
"JGDZ" VARCHAR2(256 BYTE) NULL ,
"JGMS" VARCHAR2(512 BYTE) NULL ,
"BZ" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_QX_JGXX" IS '系统-权限-机构信息';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."JGDM" IS '机构代码';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."JGMC" IS '机构名称';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."MCJP" IS '名称简拼';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."JGBM" IS '机构别名';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."JGJC" IS '机构简称';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."JCJP" IS '简称简拼';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."JGLX" IS '机构类型';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."SJJG" IS '上级机构';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."JGCJ" IS '机构层级';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."LXR" IS '联系人';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."LXRDH" IS '联系人电话';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."JGYX" IS '机构邮箱';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."JGDZ" IS '机构地址';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."JGMS" IS '机构描述';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JGXX"."BZ" IS '备注';

-- ----------------------------
-- Table structure for SYS_QX_JSQXGL
-- ----------------------------
DROP TABLE "SJSJ"."SYS_QX_JSQXGL";
CREATE TABLE "SJSJ"."SYS_QX_JSQXGL" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"JS" VARCHAR2(32 BYTE) NULL ,
"QX" VARCHAR2(256 BYTE) NULL ,
"BZ" VARCHAR2(256 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_QX_JSQXGL" IS '系统-权限-角色权限关联';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSQXGL"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSQXGL"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSQXGL"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSQXGL"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSQXGL"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSQXGL"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSQXGL"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSQXGL"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSQXGL"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSQXGL"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSQXGL"."JS" IS '角色';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSQXGL"."QX" IS '权限';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSQXGL"."BZ" IS '备注';

-- ----------------------------
-- Table structure for SYS_QX_JSXX
-- ----------------------------
DROP TABLE "SJSJ"."SYS_QX_JSXX";
CREATE TABLE "SJSJ"."SYS_QX_JSXX" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"MC" VARCHAR2(32 BYTE) NOT NULL ,
"DM" VARCHAR2(32 BYTE) NOT NULL ,
"MS" VARCHAR2(256 BYTE) NULL ,
"JSLX" VARCHAR2(32 BYTE) NULL ,
"SSYY" VARCHAR2(256 BYTE) NULL ,
"BZ" VARCHAR2(1024 BYTE) NULL ,
"ZJS" VARCHAR2(1024 BYTE) NULL ,
"JSDJ" VARCHAR2(32 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_QX_JSXX" IS '系统-权限-角色信息';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSXX"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSXX"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSXX"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSXX"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSXX"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSXX"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSXX"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSXX"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSXX"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSXX"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSXX"."MC" IS '角色名称';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSXX"."DM" IS '角色代码;角色代码采用12位字符串，每两位为一级进行编码，后续权限控制会使用此编码进行权限判定';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSXX"."MS" IS '角色描述';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSXX"."JSLX" IS '角色类型@SYS_QX_JSLX';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSXX"."SSYY" IS '所属应用@SYS_QX_APP';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSXX"."BZ" IS '备注';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSXX"."ZJS" IS '子角色;子角色编码必须属于父角色的子级';
COMMENT ON COLUMN "SJSJ"."SYS_QX_JSXX"."JSDJ" IS '角色等级';

-- ----------------------------
-- Table structure for SYS_QX_QXXX
-- ----------------------------
DROP TABLE "SJSJ"."SYS_QX_QXXX";
CREATE TABLE "SJSJ"."SYS_QX_QXXX" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"MC" VARCHAR2(256 BYTE) NOT NULL ,
"DM" VARCHAR2(256 BYTE) NOT NULL ,
"MS" VARCHAR2(256 BYTE) NULL ,
"LX" VARCHAR2(32 BYTE) NULL ,
"SSYY" VARCHAR2(256 BYTE) NULL ,
"BZ" VARCHAR2(1024 BYTE) NULL ,
"FQX" VARCHAR2(256 BYTE) NULL ,
"DZLX" VARCHAR2(32 BYTE) NULL ,
"DKFS" VARCHAR2(32 BYTE) NULL ,
"DZ" VARCHAR2(256 BYTE) NULL ,
"TB" VARCHAR2(32 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_QX_QXXX" IS '系统-权限-权限信息';
COMMENT ON COLUMN "SJSJ"."SYS_QX_QXXX"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_QX_QXXX"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_QXXX"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_QXXX"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_QX_QXXX"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_QX_QXXX"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_QX_QXXX"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_QX_QXXX"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_QX_QXXX"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_QX_QXXX"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_QX_QXXX"."MC" IS '名称';
COMMENT ON COLUMN "SJSJ"."SYS_QX_QXXX"."DM" IS '代码';
COMMENT ON COLUMN "SJSJ"."SYS_QX_QXXX"."MS" IS '描述';
COMMENT ON COLUMN "SJSJ"."SYS_QX_QXXX"."LX" IS '类型@SYS_QX_QXLX';
COMMENT ON COLUMN "SJSJ"."SYS_QX_QXXX"."SSYY" IS '所属应用@SYS_QX_APP';
COMMENT ON COLUMN "SJSJ"."SYS_QX_QXXX"."BZ" IS '备注';
COMMENT ON COLUMN "SJSJ"."SYS_QX_QXXX"."FQX" IS '父权限';
COMMENT ON COLUMN "SJSJ"."SYS_QX_QXXX"."DZLX" IS '地址类型@SYS_QX_QXDZLX';
COMMENT ON COLUMN "SJSJ"."SYS_QX_QXXX"."DKFS" IS '打开方式@SYS_QX_QXDKFS';
COMMENT ON COLUMN "SJSJ"."SYS_QX_QXXX"."DZ" IS '权限地址';
COMMENT ON COLUMN "SJSJ"."SYS_QX_QXXX"."TB" IS '图标;对应文件管理的主键';

-- ----------------------------
-- Table structure for SYS_QX_YHJSGL
-- ----------------------------
DROP TABLE "SJSJ"."SYS_QX_YHJSGL";
CREATE TABLE "SJSJ"."SYS_QX_YHJSGL" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"YH" VARCHAR2(32 BYTE) NULL ,
"JS" VARCHAR2(32 BYTE) NULL ,
"BZ" VARCHAR2(256 BYTE) NULL ,
"SHZT" VARCHAR2(32 BYTE) DEFAULT 9  NULL ,
"SHDJ" VARCHAR2(32 BYTE) DEFAULT 0  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_QX_YHJSGL" IS '系统-权限-用户角色关联';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHJSGL"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHJSGL"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHJSGL"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHJSGL"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHJSGL"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHJSGL"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHJSGL"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHJSGL"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHJSGL"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHJSGL"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHJSGL"."YH" IS '用户';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHJSGL"."JS" IS '角色';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHJSGL"."BZ" IS '备注';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHJSGL"."SHZT" IS '审核状态';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHJSGL"."SHDJ" IS '审核等级';

-- ----------------------------
-- Table structure for SYS_QX_YHXX
-- ----------------------------
DROP TABLE "SJSJ"."SYS_QX_YHXX";
CREATE TABLE "SJSJ"."SYS_QX_YHXX" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"YHXM" VARCHAR2(32 BYTE) NOT NULL ,
"YHDM" VARCHAR2(32 BYTE) NOT NULL ,
"YHMM" VARCHAR2(64 BYTE) NULL ,
"SFZH" VARCHAR2(18 BYTE) NULL ,
"YXQKS" VARCHAR2(64 BYTE) NULL ,
"YXQJS" VARCHAR2(64 BYTE) NULL ,
"SSJG" VARCHAR2(32 BYTE) DEFAULT '141B1AFC7E634176BDA7DB7F491A9004'  NULL ,
"THLX" VARCHAR2(2 BYTE) NULL ,
"YHDJ" VARCHAR2(2 BYTE) NULL ,
"YHMS" VARCHAR2(1024 BYTE) NULL ,
"YHYX" VARCHAR2(128 BYTE) NULL ,
"LXDH" VARCHAR2(256 BYTE) NULL ,
"LXDZ" VARCHAR2(256 BYTE) NULL ,
"MZ" VARCHAR2(2 BYTE) NULL ,
"GJ" VARCHAR2(5 BYTE) NULL ,
"XL" VARCHAR2(2 BYTE) NULL ,
"ZZMM" VARCHAR2(2 BYTE) NULL ,
"ZW" VARCHAR2(2 BYTE) NULL ,
"ZJ" VARCHAR2(2 BYTE) NULL ,
"BZ" VARCHAR2(1024 BYTE) NULL ,
"TX" VARCHAR2(32 BYTE) NULL ,
"XZIP" VARCHAR2(1024 BYTE) NULL ,
"SHZT" VARCHAR2(32 BYTE) DEFAULT 9  NULL ,
"SHDJ" VARCHAR2(32 BYTE) DEFAULT 0  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_QX_YHXX" IS '系统-权限-用户信息';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."YHXM" IS '用户姓名';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."YHDM" IS '用户代码';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."YHMM" IS '用户密码';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."SFZH" IS '身份证号';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."YXQKS" IS '有效期开始';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."YXQJS" IS '有效期结束';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."SSJG" IS '所属机构@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."THLX" IS '用户类型@SYS_QX_YHLX';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."YHDJ" IS '用户等级@SYS_QX_YHDJ';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."YHMS" IS '用户描述';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."YHYX" IS '用户邮箱';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."LXDH" IS '联系电话';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."LXDZ" IS '联系地址';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."MZ" IS '民族@SYS_COMMON_MZ';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."GJ" IS '国籍@SYS_COMMON_GJ';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."XL" IS '学历@SYS_COMMON_XL';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."ZZMM" IS '政治面貌@SYS_COMMON_ZZMM';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."ZW" IS '职务@SYS_QX_ZW';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."ZJ" IS '职级@SYS_QX_ZJ';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."BZ" IS '备注';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."TX" IS '头像;对应文件管理的主键';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."XZIP" IS '限制IP';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."SHZT" IS '审核状态';
COMMENT ON COLUMN "SJSJ"."SYS_QX_YHXX"."SHDJ" IS '审核等级';

-- ----------------------------
-- Table structure for SYS_SJGL_BHSC
-- ----------------------------
DROP TABLE "SJSJ"."SYS_SJGL_BHSC";
CREATE TABLE "SJSJ"."SYS_SJGL_BHSC" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"BHLB" VARCHAR2(32 BYTE) NULL ,
"DQZ" NUMBER DEFAULT 1  NULL ,
"DZL" NUMBER DEFAULT 1  NULL ,
"CSZ" NUMBER DEFAULT 1  NULL ,
"ZDZ" NUMBER DEFAULT 99999999  NULL ,
"DQZQ" VARCHAR2(32 BYTE) NULL ,
"CZZQ" VARCHAR2(32 BYTE) NULL ,
"MC" VARCHAR2(256 BYTE) NULL ,
"MS" VARCHAR2(256 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_SJGL_BHSC" IS '系统-数据管理-编号生成';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BHSC"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BHSC"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BHSC"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BHSC"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BHSC"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BHSC"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BHSC"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BHSC"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BHSC"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BHSC"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BHSC"."BHLB" IS '编号类别';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BHSC"."DQZ" IS '当前值';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BHSC"."DZL" IS '递增量';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BHSC"."CSZ" IS '初始值';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BHSC"."ZDZ" IS '最大值';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BHSC"."DQZQ" IS '当前周期';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BHSC"."CZZQ" IS '重置周期';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BHSC"."MC" IS '名称';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BHSC"."MS" IS '描述';

-- ----------------------------
-- Table structure for SYS_SJGL_BLOB
-- ----------------------------
DROP TABLE "SJSJ"."SYS_SJGL_BLOB";
CREATE TABLE "SJSJ"."SYS_SJGL_BLOB" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"NR" BLOB NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_SJGL_BLOB" IS '系统-数据管理-BLOB';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BLOB"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BLOB"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BLOB"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BLOB"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_BLOB"."NR" IS '内容';

-- ----------------------------
-- Table structure for SYS_SJGL_FILE
-- ----------------------------
DROP TABLE "SJSJ"."SYS_SJGL_FILE";
CREATE TABLE "SJSJ"."SYS_SJGL_FILE" (
"ID" VARCHAR2(256 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"YWDM" VARCHAR2(100 BYTE) NULL ,
"GLID" VARCHAR2(32 BYTE) NULL ,
"WJM" VARCHAR2(500 BYTE) NULL ,
"QCM" VARCHAR2(100 BYTE) NULL ,
"SJZT" VARCHAR2(10 BYTE) NULL ,
"SCLJ" VARCHAR2(1000 BYTE) NULL ,
"WJLX" VARCHAR2(10 BYTE) NULL ,
"WJLB" VARCHAR2(100 BYTE) NULL ,
"SJDJ" VARCHAR2(10 BYTE) DEFAULT '2'  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_SJGL_FILE" IS '系统-数据管理-文件';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_FILE"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_FILE"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_FILE"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_FILE"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_FILE"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_FILE"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_FILE"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_FILE"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_FILE"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_FILE"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_FILE"."YWDM" IS '业务代码;ZDRY_RYGL';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_FILE"."GLID" IS '关联id;前端传';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_FILE"."WJM" IS '文件名';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_FILE"."QCM" IS '去重码';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_FILE"."SJZT" IS '数据载体@SYS_SJGL_SJZT';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_FILE"."SCLJ" IS '上传路径;ZDRY_RYGL/去重码.wjlx';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_FILE"."WJLX" IS '文件类型';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_FILE"."WJLB" IS '文件类别';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_FILE"."SJDJ" IS '数据等级';

-- ----------------------------
-- Table structure for SYS_SJGL_GRBJ
-- ----------------------------
DROP TABLE "SJSJ"."SYS_SJGL_GRBJ";
CREATE TABLE "SJSJ"."SYS_SJGL_GRBJ" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"BT" VARCHAR2(256 BYTE) NULL ,
"LB" VARCHAR2(256 BYTE) DEFAULT '99'  NULL ,
"BQ" VARCHAR2(256 BYTE) NULL ,
"LX" VARCHAR2(256 BYTE) DEFAULT '02'  NULL ,
"KJX" VARCHAR2(256 BYTE) DEFAULT '01'  NULL ,
"ZT" VARCHAR2(256 BYTE) DEFAULT '01'  NULL ,
"NR" CLOB NULL ,
"JP" VARCHAR2(256 BYTE) NULL ,
"QP" VARCHAR2(1024 BYTE) NULL ,
"YDCS" NUMBER DEFAULT 0  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_SJGL_GRBJ" IS '系统-数据管理-个人笔记';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_GRBJ"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_GRBJ"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_GRBJ"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_GRBJ"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_GRBJ"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_GRBJ"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_GRBJ"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_GRBJ"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_GRBJ"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_GRBJ"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_GRBJ"."BT" IS '标题';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_GRBJ"."LB" IS '大类@SYS_SJGL_BJLB';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_GRBJ"."BQ" IS '标签';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_GRBJ"."LX" IS '类型@SYS_SJGL_BJLX';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_GRBJ"."KJX" IS '可见性@SYS_SJGL_BJKJX';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_GRBJ"."ZT" IS '状态@SYS_SJGL_BJZT';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_GRBJ"."NR" IS '内容';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_GRBJ"."JP" IS '简拼';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_GRBJ"."QP" IS '全拼';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_GRBJ"."YDCS" IS '阅读次数';

-- ----------------------------
-- Table structure for SYS_SJGL_SJDX
-- ----------------------------
DROP TABLE "SJSJ"."SYS_SJGL_SJDX";
CREATE TABLE "SJSJ"."SYS_SJGL_SJDX" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"DXDM" VARCHAR2(256 BYTE) NULL ,
"DXMC" VARCHAR2(256 BYTE) NULL ,
"DXMS" VARCHAR2(4000 BYTE) NULL ,
"DXJP" VARCHAR2(512 BYTE) NULL ,
"DXQP" VARCHAR2(512 BYTE) NULL ,
"DXLB" VARCHAR2(512 BYTE) NULL ,
"DXLX" VARCHAR2(32 BYTE) NULL ,
"DXZY" VARCHAR2(512 BYTE) NULL ,
"DXZTLX" VARCHAR2(32 BYTE) NULL ,
"DXZT" VARCHAR2(32 BYTE) DEFAULT 'default'  NULL ,
"DXGS" VARCHAR2(512 BYTE) NULL ,
"JTDX" VARCHAR2(64 BYTE) NULL ,
"ZJZD" VARCHAR2(32 BYTE) NULL ,
"QXZD" VARCHAR2(32 BYTE) NULL ,
"ZLZD" VARCHAR2(32 BYTE) NULL ,
"QCZD" VARCHAR2(32 BYTE) NULL ,
"JYZD" VARCHAR2(32 BYTE) NULL ,
"PCZD" VARCHAR2(32 BYTE) NULL ,
"YXXZD" VARCHAR2(32 BYTE) NULL ,
"FYTJXS" VARCHAR2(32 BYTE) DEFAULT '1'  NULL ,
"MRPX" VARCHAR2(256 BYTE) NULL ,
"CSCX" VARCHAR2(32 BYTE) DEFAULT '1'  NULL ,
"XQAN" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"CXTJ" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"SXXZ" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"LBFXK" VARCHAR2(8 BYTE) DEFAULT '0'  NULL ,
"BJXH" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"LJQ" VARCHAR2(512 BYTE) DEFAULT ''  NULL ,
"ZDDRSQL" CLOB NULL ,
"SQLMB" CLOB NULL ,
"CXLBKZ" CLOB NULL ,
"BJYMKZ" CLOB NULL ,
"PLYMKZ" CLOB NULL 
)
ENABLE ROW MOVEMENT
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_SJGL_SJDX" IS '系统-数据管理-数据对象';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."DXDM" IS '对象代码;代表唯一数据对象，多处使用，唯一';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."DXMC" IS '对象名称';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."DXMS" IS '对象描述';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."DXJP" IS '对象简拼';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."DXQP" IS '对象全拼';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."DXLB" IS '对象类别@SYS_SJGL_DXLB;标准对象、临时对象、系统对象等人工分类';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."DXLX" IS '对象类型@SYS_SJGL_DXLX;表、视图、excel、txt等';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."DXZY" IS '对象作用@SYS_SJGL_DXZY;增量导出、数据插入、数据更新、页面查询、页面新增、页面修改等';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."DXZTLX" IS '对象载体类型@SYS_SJGL_DXZTLX;ORACLE、POSTGRESS、MYSQL、GREEPLAM、本地文件、FTP文件、FASTDFS文件、SOLR、ES、HIVE、HBASE等';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."DXZT" IS '对象载体;根据对象载体类型不同，表示不同的具体载体，如具体数据库、ftp等';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."DXGS" IS '对象归属;数据库的某个用户、ftp的目录等';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."JTDX" IS '具体对象;数据库的表视图、文件名、文件正则等';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."ZJZD" IS '主键字段;用于查询详情等';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."QXZD" IS '权限字段;进行权限控制';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."ZLZD" IS '增量字段;进行增量抽取等';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."QCZD" IS '去重字段;用于插入更新';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."JYZD" IS '校验字段;用于存放校验信息';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."PCZD" IS '批次字段;用于存放批次号，知道具体数据来自哪次抽取等';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."YXXZD" IS '有效性字段;做逻辑删除等';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."FYTJXS" IS '分页统计形式@SYS_SJGL_FYTJXS;控制分页查询数据量统计形式，如：默认形式、异步统计、默认不统计';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."MRPX" IS '默认排序;查询时的默认排序规则';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."CSCX" IS '初始查询@SYS_COMMON_LJPD;控制查询页面是否初始化查询';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."XQAN" IS '详情按钮@SYS_COMMON_LJPD;控制是否展示';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."CXTJ" IS '查询条件@SYS_COMMON_LJPD;控制是否展示';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."SXXZ" IS '属性选择@SYS_COMMON_LJPD;控制是否展示';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."LBFXK" IS '列表复选框@SYS_COMMON_LJPD;控制是否展示';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."BJXH" IS '编辑序号@SYS_COMMON_LJPD;控制是否显示编辑页面的字段序号';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."LJQ" IS '拦截器;后台扩展系统';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."ZDDRSQL" IS '字段导入SQL;用于刷新对象字段';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."SQLMB" IS 'SQL模板;用于扩展后端，基于beetl实现';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."CXLBKZ" IS '查询列表扩展;可以扩展成各种基于数据查询的展示页面。';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."BJYMKZ" IS '编辑页面扩展;涵盖新增、修改、详情';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJDX"."PLYMKZ" IS '批量页面扩展;主要用于扩展批量上传页面';

-- ----------------------------
-- Table structure for SYS_SJGL_SJZD
-- ----------------------------
DROP TABLE "SJSJ"."SYS_SJGL_SJZD";
CREATE TABLE "SJSJ"."SYS_SJGL_SJZD" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"SJDX" VARCHAR2(32 BYTE) NULL ,
"ZDDM" VARCHAR2(32 BYTE) NULL ,
"ZDMC" VARCHAR2(128 BYTE) NULL ,
"ZDMS" VARCHAR2(256 BYTE) NULL ,
"ZDJP" VARCHAR2(256 BYTE) NULL ,
"ZDQP" VARCHAR2(1024 BYTE) NULL ,
"ZDLX" VARCHAR2(32 BYTE) NULL ,
"ZDCD" NUMBER NULL ,
"ZDKD" NUMBER DEFAULT 80  NULL ,
"ZDGD" NUMBER NULL ,
"CXMRZ" VARCHAR2(64 BYTE) NULL ,
"XZMRZ" VARCHAR2(1024 BYTE) NULL ,
"KJLX" VARCHAR2(32 BYTE) DEFAULT 'input'  NULL ,
"ZDDX" VARCHAR2(32 BYTE) DEFAULT '0'  NULL ,
"ZDFY" VARCHAR2(32 BYTE) DEFAULT '0'  NULL ,
"YXPX" VARCHAR2(8 BYTE) DEFAULT '0'  NULL ,
"LBZS" VARCHAR2(8 BYTE) DEFAULT '0'  NULL ,
"CXZS" VARCHAR2(8 BYTE) DEFAULT '0'  NULL ,
"XZZS" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"BJZS" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"XQZS" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"CXBT" VARCHAR2(8 BYTE) DEFAULT '0'  NULL ,
"BJBT" VARCHAR2(8 BYTE) DEFAULT '0'  NULL ,
"YXBJ" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"ZDZDLB" VARCHAR2(32 BYTE) NULL ,
"ZDYWLB" VARCHAR2(32 BYTE) NULL ,
"GSHFF" VARCHAR2(64 BYTE) NULL ,
"FGSHFF" VARCHAR2(64 BYTE) NULL ,
"SZHD" VARCHAR2(64 BYTE) NULL ,
"ZDTS" VARCHAR2(4000 BYTE) NULL ,
"HDYZGZ" VARCHAR2(256 BYTE) NULL ,
"QDYZGZ" VARCHAR2(256 BYTE) NULL ,
"STYLE" VARCHAR2(256 BYTE) NULL ,
"CSSL" VARCHAR2(128 BYTE) NULL ,
"QCBH" NUMBER NULL ,
"BZZD" VARCHAR2(32 BYTE) NULL ,
"MBZS" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"HDZHGZ" VARCHAR2(256 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_SJGL_SJZD" IS '系统-数据管理-数据字段';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."SJDX" IS '数据对象';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDDM" IS '字段代码';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDMC" IS '字段名称';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDMS" IS '字段描述';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDJP" IS '字段简拼';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDQP" IS '字段全拼';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDLX" IS '字段类型';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDCD" IS '字段长度';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDKD" IS '字段宽度';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDGD" IS '字段高度';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."CXMRZ" IS '查询默认值';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."XZMRZ" IS '新增默认值';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."KJLX" IS '控件类型@SYS_SJGL_KJLX;默认为1，1就是输入框，2是时间框，3是下拉框；';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDDX" IS '字典多选@SYS_COMMON_LJPD;字典下拉框是否支持多选';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDFY" IS '字典分页@SYS_COMMON_LJPD;字典下拉框是否分页展示';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."YXPX" IS '允许排序@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."LBZS" IS '列表展示@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."CXZS" IS '查询展示@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."XZZS" IS '新增展示@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."BJZS" IS '编辑展示@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."XQZS" IS '详情展示@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."CXBT" IS '查询必填@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."BJBT" IS '编辑必填@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."YXBJ" IS '允许编辑@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDZDLB" IS '字段字典类别@SYS_COMMON_ZDLB';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDYWLB" IS '字典业务类别@SYS_SJGL_ZDYWLB';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."GSHFF" IS '格式化方法;方法名称，传入参数：数据、字段描述对象、行数据';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."FGSHFF" IS '反格式化方法;方法名称，传入参数：数据、字段描述对象、行数据';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."SZHD" IS '设值回调;设置值的回调方法';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."ZDTS" IS '字段提示';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."HDYZGZ" IS '后端验证规则;人工输入';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."QDYZGZ" IS '前端验证规则;人工输入';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."STYLE" IS '前端样式;人工输入';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."CSSL" IS 'CSS类;将填充到class中';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."QCBH" IS '去重编号';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."BZZD" IS '标准字段';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."MBZS" IS '模板展示@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZD"."HDZHGZ" IS '后端转换规则;人工输入';

-- ----------------------------
-- Table structure for SYS_SJGL_SJZT
-- ----------------------------
DROP TABLE "SJSJ"."SYS_SJGL_SJZT";
CREATE TABLE "SJSJ"."SYS_SJGL_SJZT" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"DM" VARCHAR2(32 BYTE) NULL ,
"MC" VARCHAR2(128 BYTE) NULL ,
"MS" VARCHAR2(4000 BYTE) NULL ,
"JP" VARCHAR2(512 BYTE) NULL ,
"QP" VARCHAR2(512 BYTE) NULL ,
"LX" VARCHAR2(100 BYTE) NULL ,
"FWFS" VARCHAR2(100 BYTE) NULL ,
"JNDI" VARCHAR2(100 BYTE) NULL ,
"LJC" VARCHAR2(1000 BYTE) NULL ,
"YHM" VARCHAR2(100 BYTE) NULL ,
"MM" VARCHAR2(32 BYTE) NULL ,
"ZT" VARCHAR2(100 BYTE) DEFAULT '0'  NULL ,
"CSYJ" VARCHAR2(100 BYTE) NULL ,
"SJKQD" VARCHAR2(100 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_SJGL_SJZT" IS '系统-数据管理-数据载体';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."DM" IS '代码;代表唯一数据对象，多处使用，唯一';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."MC" IS '名称';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."MS" IS '描述';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."JP" IS '简拼';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."QP" IS '全拼';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."LX" IS '类型';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."FWFS" IS '访问方式';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."JNDI" IS 'JNDI名称';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."LJC" IS '连接串';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."YHM" IS '用户名';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."MM" IS '密码';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."ZT" IS '状态';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."CSYJ" IS '测试语句';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_SJZT"."SJKQD" IS '数据库驱动';

-- ----------------------------
-- Table structure for SYS_SJGL_TYZD
-- ----------------------------
DROP TABLE "SJSJ"."SYS_SJGL_TYZD";
CREATE TABLE "SJSJ"."SYS_SJGL_TYZD" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"DM" VARCHAR2(100 BYTE) NULL ,
"MC" VARCHAR2(4000 BYTE) NULL ,
"MS" VARCHAR2(4000 BYTE) NULL ,
"JP" VARCHAR2(4000 BYTE) NULL ,
"QP" VARCHAR2(4000 BYTE) NULL ,
"ZDLB" VARCHAR2(100 BYTE) NULL ,
"BZZD" VARCHAR2(100 BYTE) NULL ,
"LBSQL" VARCHAR2(4000 BYTE) NULL ,
"SJLY" VARCHAR2(300 BYTE) NULL ,
"UPNODE" VARCHAR2(100 BYTE) NULL ,
"CACHE" VARCHAR2(10 BYTE) DEFAULT '1'  NULL ,
"SJDJ" VARCHAR2(10 BYTE) DEFAULT '3'  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_SJGL_TYZD" IS '系统-数据管理-统一字典';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_TYZD"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_TYZD"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_TYZD"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_TYZD"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_TYZD"."PX" IS '排序;建议排序都按10、20、30的方式排序，方便修改穿插';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_TYZD"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_TYZD"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_TYZD"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_TYZD"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_TYZD"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_TYZD"."DM" IS '代码';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_TYZD"."MC" IS '名称';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_TYZD"."MS" IS '描述';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_TYZD"."JP" IS '简拼';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_TYZD"."QP" IS '全拼';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_TYZD"."ZDLB" IS '字典类别';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_TYZD"."BZZD" IS '标准字典;用于数据标准化等场景，如性别可以有几套字典，然后关联一个标准字典,进一步通过mc关联';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_TYZD"."LBSQL" IS '类别SQL;当次SQL为空时，字典默认在此统一字典表中，有SQL则通过SQL获取字典';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_TYZD"."SJLY" IS '数据来源';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_TYZD"."UPNODE" IS '父节点';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_TYZD"."CACHE" IS '是否缓存';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_TYZD"."SJDJ" IS '数据等级';

-- ----------------------------
-- Table structure for SYS_SJGL_YHZDY
-- ----------------------------
DROP TABLE "SJSJ"."SYS_SJGL_YHZDY";
CREATE TABLE "SJSJ"."SYS_SJGL_YHZDY" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWBM" VARCHAR2(32 BYTE) NULL ,
"SJDX" VARCHAR2(32 BYTE) NULL ,
"SJZD" VARCHAR2(32 BYTE) NULL ,
"MRZ" VARCHAR2(64 BYTE) NULL ,
"LBZS" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"CXZS" VARCHAR2(8 BYTE) DEFAULT '0'  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_SJGL_YHZDY" IS '系统-数据管理-用户自定义';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."CJRDWBM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."SJDX" IS '数据对象';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."SJZD" IS '数据字段';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."MRZ" IS '默认值';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."LBZS" IS '列表展示@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_SJGL_YHZDY"."CXZS" IS '查询展示@SYS_COMMON_LJPD';

-- ----------------------------
-- Table structure for SYS_TEST_USER
-- ----------------------------
DROP TABLE "SJSJ"."SYS_TEST_USER";
CREATE TABLE "SJSJ"."SYS_TEST_USER" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"YHXM" VARCHAR2(32 BYTE) NOT NULL ,
"YHDM" VARCHAR2(32 BYTE) NOT NULL ,
"YHMM" VARCHAR2(64 BYTE) NULL ,
"SFZH" VARCHAR2(18 BYTE) NULL ,
"YXQKS" VARCHAR2(64 BYTE) NULL ,
"YXQJS" VARCHAR2(64 BYTE) NULL ,
"SSJG" VARCHAR2(32 BYTE) NULL ,
"THLX" VARCHAR2(2 BYTE) NULL ,
"YHDJ" VARCHAR2(2 BYTE) NULL ,
"YHMS" VARCHAR2(1024 BYTE) NULL ,
"YHYX" VARCHAR2(32 BYTE) NULL ,
"LXDH" VARCHAR2(32 BYTE) NULL ,
"LXDZ" VARCHAR2(256 BYTE) NULL ,
"MZ" VARCHAR2(2 BYTE) NULL ,
"GJ" VARCHAR2(5 BYTE) NULL ,
"XL" VARCHAR2(2 BYTE) NULL ,
"ZZMM" VARCHAR2(2 BYTE) NULL ,
"ZW" VARCHAR2(2 BYTE) NULL ,
"ZJ" VARCHAR2(2 BYTE) NULL ,
"BZ" VARCHAR2(1024 BYTE) NULL ,
"TX" VARCHAR2(32 BYTE) NULL ,
"XZIP" VARCHAR2(1024 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_TEST_USER" IS '系统-测试-用户';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."YHXM" IS '用户姓名';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."YHDM" IS '用户代码';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."YHMM" IS '用户密码';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."SFZH" IS '身份证号';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."YXQKS" IS '有效期开始';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."YXQJS" IS '有效期结束';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."SSJG" IS '所属机构@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."THLX" IS '用户类型@SYS_QX_YHLX';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."YHDJ" IS '用户等级@SYS_QX_YHDJ';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."YHMS" IS '用户描述';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."YHYX" IS '用户邮箱';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."LXDH" IS '联系电话';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."LXDZ" IS '联系地址';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."MZ" IS '民族@SYS_COMMON_MZ';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."GJ" IS '国籍@SYS_COMMON_GJ';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."XL" IS '学历@SYS_COMMON_XL';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."ZZMM" IS '政治面貌@SYS_COMMON_ZZMM';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."ZW" IS '职务@SYS_QX_ZW';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."ZJ" IS '职级@SYS_QX_ZJ';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."BZ" IS '备注';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."TX" IS '头像;对应文件管理的主键';
COMMENT ON COLUMN "SJSJ"."SYS_TEST_USER"."XZIP" IS '限制IP';

-- ----------------------------
-- Table structure for SYS_XMGL_RWXX
-- ----------------------------
DROP TABLE "SJSJ"."SYS_XMGL_RWXX";
CREATE TABLE "SJSJ"."SYS_XMGL_RWXX" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"APP" VARCHAR2(32 BYTE) NULL ,
"RWMC" VARCHAR2(256 BYTE) NULL ,
"RWMS" CLOB NULL ,
"RWDJ" VARCHAR2(32 BYTE) NULL ,
"KSSJ" VARCHAR2(14 BYTE) NULL ,
"JSSJ" VARCHAR2(14 BYTE) NULL ,
"SJYQ" VARCHAR2(256 BYTE) NULL ,
"DQZT" VARCHAR2(32 BYTE) NULL ,
"FZR" VARCHAR2(32 BYTE) NULL ,
"KFRY" VARCHAR2(256 BYTE) NULL ,
"KHDJR" VARCHAR2(256 BYTE) NULL ,
"RWBZ" VARCHAR2(4000 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_XMGL_RWXX" IS '系统-项目管理-任务信息';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."APP" IS '应用@SYS_QX_APP';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."RWMC" IS '任务名称';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."RWMS" IS '任务描述';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."RWDJ" IS '任务等级@SYS_COMMON_DJ';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."KSSJ" IS '开始时间';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."JSSJ" IS '结束时间';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."SJYQ" IS '时间要求';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."DQZT" IS '当前状态';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."FZR" IS '负责人@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."KFRY" IS '开发人员@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."KHDJR" IS '客户对接人@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_XMGL_RWXX"."RWBZ" IS '任务备注';

-- ----------------------------
-- Table structure for SYS_YXJK_JKRW
-- ----------------------------
DROP TABLE "SJSJ"."SYS_YXJK_JKRW";
CREATE TABLE "SJSJ"."SYS_YXJK_JKRW" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"RWLX" VARCHAR2(32 BYTE) NOT NULL ,
"JTRW" VARCHAR2(32 BYTE) NOT NULL ,
"LXRXM" VARCHAR2(1024 BYTE) NULL ,
"LXRDM" VARCHAR2(1024 BYTE) NULL ,
"LXDWMC" VARCHAR2(256 BYTE) NULL ,
"LXDWDM" VARCHAR2(32 BYTE) NULL ,
"YLRW" VARCHAR2(512 BYTE) NULL ,
"RWZT" VARCHAR2(32 BYTE) DEFAULT '0'  NOT NULL ,
"RWDJ" VARCHAR2(32 BYTE) DEFAULT '1'  NOT NULL ,
"CLFK" VARCHAR2(256 BYTE) NULL ,
"JCSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NOT NULL ,
"XXMB" VARCHAR2(512 BYTE) NULL ,
"YCYY" VARCHAR2(4000 BYTE) NULL ,
"RWMC" VARCHAR2(256 BYTE) NOT NULL ,
"RWLB" VARCHAR2(32 BYTE) DEFAULT '99'  NULL ,
"RWPCH" VARCHAR2(64 BYTE) NULL ,
"RWDM" VARCHAR2(64 BYTE) NOT NULL ,
"RWDS" VARCHAR2(64 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_YXJK_JKRW" IS '系统-运行监控-监控任务';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."PX" IS '排序;按顺序监控';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."RWLX" IS '任务类型@SYS_YXJK_RWLX;监控任务的类型';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."JTRW" IS '具体任务';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."LXRXM" IS '联系人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."LXRDM" IS '联系人代码@SYS_COMMON_USER;可选，多选，会收到短信和工作平台消息';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."LXDWMC" IS '联系单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."LXDWDM" IS '联系单位代码@SYS_COMMON_ORG;可选，会收到短信和工作平台消息';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."YLRW" IS '依赖任务';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."RWZT" IS '任务状态@SYS_COMMON_ZT;最新';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."RWDJ" IS '任务等级@SYS_COMMON_DJ';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."CLFK" IS '处理反馈;人工反馈处理进度，生成消息，按异常消息渠道发送消息给相关联系人';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."JCSJ" IS '监测时间;最新一次进行数据库状态监测的时间';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."XXMB" IS '消息模板;监控到异常时根据此模板生成预警消息';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."YCYY" IS '异常原因;监控系统生成，实际异常信息，具体问题定位';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."RWMC" IS '任务名称';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."RWLB" IS '任务类别;人工业务上的分类';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."RWPCH" IS '任务批次号';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."RWDM" IS '任务代码';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_JKRW"."RWDS" IS '任务定时;为空表示持续执行';

-- ----------------------------
-- Table structure for SYS_YXJK_XX
-- ----------------------------
DROP TABLE "SJSJ"."SYS_YXJK_XX";
CREATE TABLE "SJSJ"."SYS_YXJK_XX" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"JKRW" VARCHAR2(32 BYTE) NULL ,
"XXLX" VARCHAR2(32 BYTE) NULL ,
"YCYY" VARCHAR2(4000 BYTE) NULL ,
"XXNR" VARCHAR2(256 BYTE) NULL ,
"XXDJ" VARCHAR2(32 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_YXJK_XX" IS '系统-运行监控-消息';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_XX"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_XX"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_XX"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_XX"."YXX" IS '有效性@SYS_COMMON_LJPD;无效的消息不发送';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_XX"."PX" IS '排序;按顺序监控';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_XX"."JKRW" IS '监控任务';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_XX"."XXLX" IS '消息类型@SYS_YXJK_XXLX;异常、恢复，跟进';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_XX"."YCYY" IS '异常原因;监控系统生成，实际异常信息，具体问题定位';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_XX"."XXNR" IS '消息内容;通过消息模板生成';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_XX"."XXDJ" IS '消息等级@SYS_COMMON_JJCD';

-- ----------------------------
-- Table structure for SYS_YXJK_ZDYSQL
-- ----------------------------
DROP TABLE "SJSJ"."SYS_YXJK_ZDYSQL";
CREATE TABLE "SJSJ"."SYS_YXJK_ZDYSQL" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"DM" VARCHAR2(32 BYTE) NULL ,
"MC" VARCHAR2(128 BYTE) NULL ,
"MS" VARCHAR2(4000 BYTE) NULL ,
"JP" VARCHAR2(512 BYTE) NULL ,
"QP" VARCHAR2(512 BYTE) NULL ,
"SQL" VARCHAR2(4000 BYTE) NULL ,
"ZT" VARCHAR2(32 BYTE) NULL ,
"SJK" VARCHAR2(128 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."SYS_YXJK_ZDYSQL" IS '系统-运行监控-自定义sql';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."DM" IS '代码;代表唯一数据对象，多处使用，唯一';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."MC" IS '名称';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."MS" IS '描述';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."JP" IS '简拼';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."QP" IS '全拼';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."SQL" IS '自定义sql';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."ZT" IS '状态@SYS_COMMON_ZT';
COMMENT ON COLUMN "SJSJ"."SYS_YXJK_ZDYSQL"."SJK" IS '数据库@SYS_COMMON_SJZT';

-- ----------------------------
-- Table structure for TEMP_LOG_FWZR
-- ----------------------------
DROP TABLE "SJSJ"."TEMP_LOG_FWZR";
CREATE TABLE "SJSJ"."TEMP_LOG_FWZR" (
"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"CJSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"GXSJ" VARCHAR2(14 BYTE) DEFAULT to_char(sysdate,'yyyymmddhh24miss')  NULL ,
"YXX" VARCHAR2(8 BYTE) DEFAULT '1'  NULL ,
"PX" NUMBER DEFAULT 99999  NULL ,
"KZXX" VARCHAR2(4000 BYTE) DEFAULT '{}'  NULL ,
"CJRXM" VARCHAR2(64 BYTE) NULL ,
"CJRDM" VARCHAR2(32 BYTE) NULL ,
"CJRDWMC" VARCHAR2(256 BYTE) NULL ,
"CJRDWDM" VARCHAR2(32 BYTE) NULL ,
"SJDX" VARCHAR2(32 BYTE) NULL ,
"CZIP" VARCHAR2(32 BYTE) NULL ,
"CZLX" VARCHAR2(32 BYTE) NULL ,
"URL" VARCHAR2(4000 BYTE) NULL ,
"XGCS" VARCHAR2(4000 BYTE) NULL ,
"TOKEN" VARCHAR2(32 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SJSJ"."TEMP_LOG_FWZR" IS '系统-日志-访问日志';
COMMENT ON COLUMN "SJSJ"."TEMP_LOG_FWZR"."ID" IS '主键';
COMMENT ON COLUMN "SJSJ"."TEMP_LOG_FWZR"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "SJSJ"."TEMP_LOG_FWZR"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "SJSJ"."TEMP_LOG_FWZR"."YXX" IS '有效性@SYS_COMMON_LJPD';
COMMENT ON COLUMN "SJSJ"."TEMP_LOG_FWZR"."PX" IS '排序';
COMMENT ON COLUMN "SJSJ"."TEMP_LOG_FWZR"."KZXX" IS '扩展信息;JSON格式';
COMMENT ON COLUMN "SJSJ"."TEMP_LOG_FWZR"."CJRXM" IS '创建人姓名';
COMMENT ON COLUMN "SJSJ"."TEMP_LOG_FWZR"."CJRDM" IS '创建人代码@SYS_COMMON_USER';
COMMENT ON COLUMN "SJSJ"."TEMP_LOG_FWZR"."CJRDWMC" IS '创建人单位名称';
COMMENT ON COLUMN "SJSJ"."TEMP_LOG_FWZR"."CJRDWDM" IS '创建人单位代码@SYS_COMMON_ORG';
COMMENT ON COLUMN "SJSJ"."TEMP_LOG_FWZR"."SJDX" IS '数据对象';
COMMENT ON COLUMN "SJSJ"."TEMP_LOG_FWZR"."CZIP" IS '操作ip';
COMMENT ON COLUMN "SJSJ"."TEMP_LOG_FWZR"."CZLX" IS '操作类型';
COMMENT ON COLUMN "SJSJ"."TEMP_LOG_FWZR"."URL" IS 'URL';
COMMENT ON COLUMN "SJSJ"."TEMP_LOG_FWZR"."XGCS" IS '相关参数';
COMMENT ON COLUMN "SJSJ"."TEMP_LOG_FWZR"."TOKEN" IS '权限id';

-- ----------------------------
-- View structure for V_XNDX
-- ----------------------------
CREATE OR REPLACE FORCE VIEW "SJSJ"."V_XNDX" AS 
select '' id,1 repeat from dual;

-- ----------------------------
-- Function structure for DES_DE
-- ----------------------------
CREATE OR REPLACE FUNCTION "SJSJ"."DES_DE" (p_text IN STRING,p_pwd IN STRING)
   RETURN String
IS
   LANGUAGE JAVA
   NAME 'Desutil.decrypt(java.lang.String,java.lang.String) return String';
/

-- ----------------------------
-- Function structure for DES_EN
-- ----------------------------
CREATE OR REPLACE FUNCTION "SJSJ"."DES_EN" (p_text IN STRING,p_pwd IN STRING)
   RETURN String
IS
   LANGUAGE JAVA
   NAME 'Desutil.encrypt(java.lang.String,java.lang.String) return String';
/

-- ----------------------------
-- Function structure for LONG_TO_CHAR
-- ----------------------------
CREATE OR REPLACE FUNCTION "SJSJ"."LONG_TO_CHAR"( in_rowid rowid,in_owner
varchar,in_table_name varchar,in_column varchar2)
RETURN varchar AS
text_c1 varchar2(32767);
sql_cur varchar2(2000);
--
begin
  sql_cur := 'select '||in_column||' from
'||in_owner||'.'||in_table_name||' where rowid =
'||chr(39)||in_rowid||chr(39);
  dbms_output.put_line (sql_cur);
  execute immediate sql_cur into text_c1;

  text_c1 := substr(text_c1, 1, 4000);
  RETURN TEXT_C1;
END;
/

-- ----------------------------
-- Function structure for MD5
-- ----------------------------
CREATE OR REPLACE FUNCTION "SJSJ"."MD5"(in_str IN VARCHAR2)
RETURN VARCHAR2
IS
retval varchar2(32);
BEGIN
retval := utl_raw.cast_to_raw(DBMS_OBFUSCATION_TOOLKIT.MD5(INPUT_STRING => in_str));
--dbms_output.put_line('<'||in_str||'>的MD5:'||retval);
RETURN retval;
END;
/

-- ----------------------------
-- Indexes structure for table JCGA_JCYG_JCXX
-- ----------------------------

-- ----------------------------
-- Checks structure for table JCGA_JCYG_JCXX
-- ----------------------------
ALTER TABLE "SJSJ"."JCGA_JCYG_JCXX" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table JCGA_JCYG_JCXX
-- ----------------------------
ALTER TABLE "SJSJ"."JCGA_JCYG_JCXX" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table JCGA_JCYG_SHGX
-- ----------------------------

-- ----------------------------
-- Checks structure for table JCGA_JCYG_SHGX
-- ----------------------------
ALTER TABLE "SJSJ"."JCGA_JCYG_SHGX" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table JCGA_JCYG_SHGX
-- ----------------------------
ALTER TABLE "SJSJ"."JCGA_JCYG_SHGX" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_LOG_FWZR
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_LOG_FWZR
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_LOG_FWZR" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_LOG_FWZR" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_LOG_FWZR
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_LOG_FWZR" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_LOG_HTRZ
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_LOG_HTRZ
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_LOG_HTRZ" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_LOG_HTRZ
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_LOG_HTRZ" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table SYS_LOG_SJLZRZ
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_LOG_SJLZRZ" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Checks structure for table SYS_LOG_SJSCCW
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_LOG_SJSCCW" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Checks structure for table SYS_PTGL_YJFK
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_PTGL_YJFK" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Indexes structure for table SYS_QX_APP
-- ----------------------------
CREATE UNIQUE INDEX "SJSJ"."IDX_SYS_QX_APP_DM"
ON "SJSJ"."SYS_QX_APP" ("DM" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table SYS_QX_APP
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_APP" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_QX_APP
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_APP" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_QX_FWQ
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_QX_FWQ
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_FWQ" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_QX_FWQ
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_FWQ" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_QX_JGXX
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_QX_JGXX
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_JGXX" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_QX_JGXX" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_QX_JGXX
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_JGXX" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_QX_JSQXGL
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_QX_JSQXGL
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_JSQXGL" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_QX_JSQXGL
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_JSQXGL" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_QX_JSXX
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_QX_JSXX
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_JSXX" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_QX_JSXX" ADD CHECK ("MC" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_QX_JSXX" ADD CHECK ("DM" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_QX_JSXX
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_JSXX" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_QX_QXXX
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_QX_QXXX
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_QXXX" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_QX_QXXX" ADD CHECK ("MC" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_QX_QXXX" ADD CHECK ("DM" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_QX_QXXX
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_QXXX" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_QX_YHJSGL
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_QX_YHJSGL
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_YHJSGL" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_QX_YHJSGL
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_YHJSGL" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_QX_YHXX
-- ----------------------------
CREATE UNIQUE INDEX "SJSJ"."IDX_SYS_QX_YHXX_YHDM"
ON "SJSJ"."SYS_QX_YHXX" ("YHDM" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table SYS_QX_YHXX
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_YHXX" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_QX_YHXX" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_QX_YHXX" ADD CHECK ("YHXM" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_QX_YHXX" ADD CHECK ("YHDM" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_QX_YHXX
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_QX_YHXX" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_SJGL_BHSC
-- ----------------------------
CREATE INDEX "SJSJ"."SYS_SJGL_BHSC_BHLB"
ON "SJSJ"."SYS_SJGL_BHSC" ("BHLB" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table SYS_SJGL_BHSC
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_BHSC" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_SJGL_BHSC
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_BHSC" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_SJGL_BLOB
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_SJGL_BLOB
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_BLOB" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_SJGL_BLOB
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_BLOB" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_SJGL_FILE
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_SJGL_FILE
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_FILE" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_SJGL_FILE
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_FILE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table SYS_SJGL_GRBJ
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_GRBJ" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Indexes structure for table SYS_SJGL_SJDX
-- ----------------------------
CREATE UNIQUE INDEX "SJSJ"."IDX_SYS_SJGL_SJDX_DXDM"
ON "SJSJ"."SYS_SJGL_SJDX" ("DXDM" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table SYS_SJGL_SJDX
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_SJDX" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_SJGL_SJDX" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_SJGL_SJDX
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_SJDX" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_SJGL_SJZD
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_SJGL_SJZD
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_SJZD" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_SJGL_SJZD" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_SJGL_SJZD
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_SJZD" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_SJGL_SJZT
-- ----------------------------
CREATE UNIQUE INDEX "SJSJ"."IDX_SYS_SJGL_SJK_DM"
ON "SJSJ"."SYS_SJGL_SJZT" ("DM" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table SYS_SJGL_SJZT
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_SJZT" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_SJGL_SJZT
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_SJZT" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_SJGL_TYZD
-- ----------------------------
CREATE INDEX "SJSJ"."IDX_SYS_SJGL_TYZD_DM"
ON "SJSJ"."SYS_SJGL_TYZD" ("DM" ASC)
LOGGING
VISIBLE;
CREATE INDEX "SJSJ"."IDX_SYS_SJGL_TYZD_ZDLB"
ON "SJSJ"."SYS_SJGL_TYZD" ("ZDLB" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table SYS_SJGL_TYZD
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_TYZD" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_SJGL_TYZD
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_TYZD" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_SJGL_YHZDY
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_SJGL_YHZDY
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_YHZDY" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_SJGL_YHZDY" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_SJGL_YHZDY
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_SJGL_YHZDY" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table SYS_TEST_USER
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_TEST_USER" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_TEST_USER" ADD CHECK ("YHXM" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_TEST_USER" ADD CHECK ("YHDM" IS NOT NULL);

-- ----------------------------
-- Indexes structure for table SYS_XMGL_RWXX
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_XMGL_RWXX
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_XMGL_RWXX" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_XMGL_RWXX
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_XMGL_RWXX" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_YXJK_JKRW
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_YXJK_JKRW
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_YXJK_JKRW" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_YXJK_JKRW" ADD CHECK ("RWLX" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_YXJK_JKRW" ADD CHECK ("JTRW" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_YXJK_JKRW" ADD CHECK ("RWZT" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_YXJK_JKRW" ADD CHECK ("RWDJ" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_YXJK_JKRW" ADD CHECK ("JCSJ" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_YXJK_JKRW" ADD CHECK ("RWMC" IS NOT NULL);
ALTER TABLE "SJSJ"."SYS_YXJK_JKRW" ADD CHECK ("RWDM" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_YXJK_JKRW
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_YXJK_JKRW" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_YXJK_XX
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_YXJK_XX
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_YXJK_XX" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_YXJK_XX
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_YXJK_XX" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SYS_YXJK_ZDYSQL
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_YXJK_ZDYSQL
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_YXJK_ZDYSQL" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_YXJK_ZDYSQL
-- ----------------------------
ALTER TABLE "SJSJ"."SYS_YXJK_ZDYSQL" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table TEMP_LOG_FWZR
-- ----------------------------

-- ----------------------------
-- Checks structure for table TEMP_LOG_FWZR
-- ----------------------------
ALTER TABLE "SJSJ"."TEMP_LOG_FWZR" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table TEMP_LOG_FWZR
-- ----------------------------
ALTER TABLE "SJSJ"."TEMP_LOG_FWZR" ADD PRIMARY KEY ("ID");
