
xxl:
  job:
    enable: false
    #  enable: true
    admin:
      #    addresses: http://124.220.197.217:9162/xxl-job-admin
      addresses: http://127.0.0.1:8080/xxl-job-admin
      username: admin
      password: 123456
    accessToken: default_token
    executor:
      appname: sjsj
      address: ''
      ip: ''
      port: 9999
      logpath: /benma666/logs/xxl-job/jobhandler
      logretentiondays: 30
