benma666:
  # 调试模式
  debug: true
  # 默认需要自动通过主键去获取数据库里记录的方法。
  mrputobj: save,update
  login:
    dlsbcs: 5
  service:
    addr: /index
  ljq:
    # 可以是springboot的bean名称（从容器中获取）或者具体的完整类路径（反射实例化，springboot的注解不会生效）
    default: MyDefaultLjq
  xtqx:
    # 没有创建权限时，默认通过的方法
    mrtgqx: dxjcxx,select
    # 授权模式，cllx（精确到处理类型），sjdx（只要相关数据对象有授权就可以使用其下所有方法），authCode（只要对应授权码有授权就可以使用其下所有方法），默认为cllx
    sqms: cllx
  config:
    list: SYS_COMMON_APPCONFIG,SYS_MYSERVICE_APPCONFIG,SYS_SJGL_APPCONFIG,SYS_KP_APPCONFIG
  data:
    password: xxx
  fwq:
    ejmm: xxx
  sjzt:
    ejmm: xxx
  yhxx:
    ejmm: xxx
  app:
    ejmm: xxx
    dm: sjsj

server:
  # 服务器的HTTP端口，默认为8080
  port: 8090
  servlet:
    # 应用的访问路径
    context-path: "/sjsj-ht"
    session:
      #单位(s)  这里是24小时
      timeout: 24h
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值25
      min-spare: 30

spring:
  application:
    name: 数据世界
  profiles:
    active: oracle
#    active: mysql
    include:
      - private
      - xxljob
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n.message
    encoding: UTF-8
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  100MB
      # 设置总上传的文件大小
      max-request-size:  100MB
      # 上传临时目录
      location: /tmp/sjsj/upload
      # 文件大小达到该阈值，将写入临时目录，默认为0，即所有文件都会直接写入磁盘临时文件中。
      file-size-threshold: 0B
      # 是否惰性处理请求，默认为false。
      resolveLazily: true
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:mydb
    username: sjsj2
    password: sjsj
    dbtype: oracle
#    url: jdbc:mysql://127.0.0.1:3307/sjsj2?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
#    username: sjsj2
#    password: sjsj
#    dbtype: mysql
    druid:
      # 初始连接数
      initial-size: 2
      # 最小连接池数量
      min-idle: 2
      # 最大连接池数量
      max-active: 50
      # 配置获取连接等待超时的时间
      max-wait: 300000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 600000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      max-evictable-idle-time-millis: 900000
      # 配置检测连接是否有效
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: jingma
        login-password: jingma
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 10000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
        slf4j:
          #打开日志
          enabled: true
          #关闭合并参数的sql
          statement-executable-sql-log-enable: true
          #关闭创建sql日志
          statement-create-after-log-enabled: false
          #sql预编译后
          statement-prepare-after-log-enabled: false
          #关闭参数
          statement-parameter-set-log-enabled: false
          statement-parameter-clear-log-enable: false
          #执行后
          statement-execute-after-log-enabled: false
          #关闭后
          statement-close-after-log-enabled: false
          #执行后，含有执行耗时
          statement-execute-batch-after-log-enabled: false
          statement-execute-query-after-log-enabled: false
          statement-execute-update-after-log-enabled: false
  redis:
    # 是否使用redis
    enabled: false
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 30s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# actuator 监控配置
management:
  #actuator端口 如果不配置做默认使用上面8080端口
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        #默认值访问health,info端点  用*可以包含全部端点
        include: "*"
      #修改访问路径 2.0之前默认是/; 2.0默认是/actuator可以通过这个属性值修改
      base-path: /actuator
  endpoint:
    shutdown:
      enabled: true #打开shutdown端点
    health:
      show-details: always #获得健康检查中所有指标的详细信息

# 日志配置
logging:
  #pattern: "%d{MM-dd HH:mm:ss} %-5level [%t] %logger{30}.%M:%L - %msg%n"
  #pattern-db: "{'scff':'%M','sch':'%L','message':'%m','threadName':'%t','level':'%level','ssxm':'%cn','loggerName':'%logger{30}','cjsj':'%date{yyyyMMddHHmmss}','gxsj':'%date{yyyyMMddHHmmss}'}"
  file:
    path: /benma666/logs
  level:
    root: info
    cn.benma666: debug
    org.springframework.core: debug
    druid.sql.Statement: debug
  logback:
    mylog:
      #level: ERROR
      #insert-sql: insert into SYS_LOG_HTRZ(id,cjsj,gxsj,xc,jb,scl,scff,sch,xx,ssxm) values(#{id},#{cjsj},#{gxsj},#{threadName},#{level},#{loggerName},#{scff},#{sch},#{message},#{ssxm})
    rollingpolicy:
      #max-file-size: 20MB
