# 基础镜像
FROM  openjdk:8-jre
# 通过镜像标签声明了作者信息
LABEL maintainer="jingma"

# 挂载目录
VOLUME /benma666
# 指定路径
WORKDIR /benma666/sjsj
# 启动服务
#ENTRYPOINT ["/benma666/sjsj/docker.sh"]
ENTRYPOINT ["java", "-cp", "sjsj.jar:lib/*", "cn.benma666.sjsj.SjsjApplication", "--spring.config.location=application.yaml"]
