
### 登陆
POST {{serviceAddr}}
Content-Type: application/json

{
  "sjdx":{
    "dxdm":"SYS_QX_YHXX_MRDL"
  },
  "yobj": {
    "yhdm":"sys",
    "yhmm":"sys_123"
  },
  "sys":{
    "cllx":"yhdl",
    "token":"4978866291C611DA0D2D5999C413107F",
    "clearCache":false
  }
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "请求异常："+response.body);
});
%}

### 刷新用户权限
POST {{serviceAddr}}
Content-Type: application/json

{
  "sjdx":{
    "dxdm":"SYS_QX_YHXX_MRDL"
  },
  "sys":{
    "cllx":"sxyhqx",
    "token":"4978866291C611DA0D2D5999C413107F",
    "clearCache":false
  }
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "请求异常："+response.body);
});
%}

### 系统基础信息
POST {{serviceAddr}}
Content-Type: application/json

{
  "sjdx":{
    "dxdm":"SYS_SJGL_SJDX"
  },
  "yobj": {
  },
  "sys":{
    "cllx":"xtjcxx",
    "token":"4978866291C611DA0D2D5999C413107F"
  }
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "请求异常："+response.body);
});
%}

### 对象基础信息
POST {{serviceAddr}}
Content-Type: application/json

{
  "sjdx":{
    "dxdm":"SYS_SJGL_SJDX"
  },
  "yobj": {
  },
  "sys":{
    "cllx":"dxjcxx",
    "token":"4978866291C611DA0D2D5999C413107F"
  }
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "请求异常："+response.body);
});
%}

### 清除字典缓存
POST {{serviceAddr}}
Content-Type: application/json

{
  "sjdx":{
    "dxdm":"SYS_SJGL_TYZD"
  },
  "yobj": {
  },
  "sys":{
    "cllx":"qchc",
    "token":"4978866291C611DA0D2D5999C413107F"
  }
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "请求异常："+response.body);
});
%}

### 查询数据缓存
POST {{serviceAddr}}
Content-Type: application/json

{
  "sjdx":{
    "dxdm":"SYS_COMMON_CACHE"
  },
  "yobj": {
  },
  "sys":{
    "cllx":"select",
    "token":"4978866291C611DA0D2D5999C413107F"
  }
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "请求异常："+response.body);
});
%}

### 清除数据缓存
POST {{serviceAddr}}
Content-Type: application/json

{
  "sjdx":{
    "dxdm":"SYS_COMMON_CACHE"
  },
  "yobj": {
    "key": "fields"
  },
  "sys":{
    "cllx":"qchc",
    "token":"4978866291C611DA0D2D5999C413107F"
  }
}

### 用户退出
POST {{serviceAddr}}
Content-Type: application/json

{
  "sjdx":{
    "dxdm":"SYS_QX_YHXX_MRDL"
  },
  "sys":{
    "cllx":"yhtc",
    "token":"4978866291C611DA0D2D5999C413107F",
    "clearCache":false
  }
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "请求异常："+response.body);
});
%}


