
### 对象基础信息
POST {{serviceAddr}}
Content-Type: application/json

{
  "sjdx":{
    "dxdm":"SYS_SJGL_TYZD_DEMO"
  },
  "yobj": {
    "id": "0E369823CC1A45E88ED6BE8E8F7DCBC0"
  },
  "sys":{
    "cllx":"dxjcxx",
    "token":"4978866291C611DA0D2D5999C413107F"
  }
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "请求异常："+response.body);
});
%}

### 查询数据
POST {{serviceAddr}}
Content-Type: application/json

{
  "sjdx":{
    "dxdm":"SYS_SJGL_TYZD_DEMO"
  },
  "yobj": {
    "dm": "3424111"
  },
  "page": {
    "pageNumber": "1",
    "pageSize": "10",
  },
  "sys":{
    "cllx":"select",
    "token":"4978866291C611DA0D2D5999C413107F"
  }
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "请求异常："+response.body);
});
%}

### 模板下载
POST {{serviceAddr}}
Content-Type: application/json

{
  "sjdx":{
    "dxdm":"SYS_SJGL_TYZD_DEMO"
  },
  "sys":{
    "cllx":"dcmb",
    "token":"4978866291C611DA0D2D5999C413107F"
  },
  "yobj": {
  }
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "请求异常："+response.body);
});
%}

### 模板下载
GET {{serviceAddr}}?sjdx.dxdm=SYS_SJGL_TYZD_DEMO&sys.cllx=dcmb&sys.token=4978866291C611DA0D2D5999C413107F

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "请求异常："+response.body);
});
%}

### 数据批量上传
POST {{serviceAddr}}
Content-Type: application/json

{
  "sjdx":{
    "dxdm":"SYS_SJGL_TYZD_DEMO"
  },
  "yobj": {
    "dm": "3424111"
  },
  "page": {
    "pageNumber": "1",
    "pageSize": "10",
  },
  "sys":{
    "cllx":"sjplsc",
    "token":"4978866291C611DA0D2D5999C413107F",
    "fiels": []
  }
}

### 导出当前页
POST {{serviceAddr}}
Content-Type: application/json

{
  "sjdx":{
    "dxdm":"SYS_SJGL_TYZD_DEMO"
  },
  "sys":{
    "cllx":"dcdqysj",
    "token":"4978866291C611DA0D2D5999C413107F"
  },
  "yobj": {
    "dm": "3424111"
  }
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "请求异常："+response.body);
});
%}

### 导出全部
POST {{serviceAddr}}
Content-Type: application/json

{
  "sjdx":{
    "dxdm":"SYS_SJGL_TYZD_DEMO"
  },
  "sys":{
    "cllx":"dcsj",
    "token":"4978866291C611DA0D2D5999C413107F"
  },
  "yobj": {
    "dm": "3424111"
  },
  "page": {
    "pageSize": 50000
  }
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "请求异常："+response.body);
});
%}

### 新建记录
POST {{serviceAddr}}
Content-Type: application/json

{
  "sjdx":{
    "dxdm":"SYS_SJGL_TYZD_DEMO"
  },
  "yobj": {
    "id": "A9C5C1D9E70D4BC09FA33E4360A1A387",
    "yxx": "1",
    "dm": "test",
    "mc": "测试",
    "zdlb": "SYS_COMMON_ZDLB"
  },
  "sys":{
    "cllx":"insert",
    "token":"4978866291C611DA0D2D5999C413107F"
  }
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "请求异常："+response.body);
});
%}

### 修改数据
POST {{serviceAddr}}
Content-Type: application/json

{
  "sjdx":{
    "dxdm":"SYS_SJGL_TYZD_DEMO"
  },
  "yobj": {
    "id": "A9C5C1D9E70D4BC09FA33E4360A1A387",
    "mc": "测试-系统-数据管理-数据对象-2"
  },
  "sys":{
    "cllx":"update",
    "token":"4978866291C611DA0D2D5999C413107F"
  }
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "请求异常："+response.body);
});
%}

### 单个删除数据
POST {{serviceAddr}}
Content-Type: application/json

{
  "sjdx":{
    "dxdm":"SYS_SJGL_TYZD_DEMO"
  },
  "sys":{
    "ids": ["A9C5C1D9E70D4BC09FA33E4360A1A387"],
    "cllx":"delete",
    "token":"4978866291C611DA0D2D5999C413107F"
  }
}

### 批量删除数据
POST {{serviceAddr}}
Content-Type: application/json

{
  "sjdx":{
    "dxdm":"SYS_SJGL_TYZD_DEMO"
  },
  "sys":{
    "ids": ["A9C5C1D9E70D4BC09FA33E4360A1A387"],
    "cllx":"plsc",
    "token":"4978866291C611DA0D2D5999C413107F"
  }
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "请求异常："+response.body);
});
%}