version : '3.8'
name: sjsj
services:
  benma666-mysql:
    container_name: benma666-mysql
    image: benma666-mysql
    build:
      context: ./mysql
    ports:
      - "3316:3306"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/mysql/conf:/etc/mysql/conf.d
      - ./data/mysql/logs:/logs
      - ./data/mysql/data:/var/lib/mysql
    command: [
        'mysqld',
        '--innodb-buffer-pool-size=80M',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-time-zone=+8:00',
        '--lower-case-table-names=1'
    ]
    environment:
      MYSQL_DATABASE: 'sjsj2_zs'
      MYSQL_ROOT_PASSWORD: password
  benma666-redis:
    container_name: benma666-redis
    image: benma666-redis
    build:
      context: ./redis
    ports:
      - "6389:6379"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/redis/redis.conf:/benma666/redis/redis.conf
      - ./data/redis/data:/data
    command: redis-server /benma666/redis/redis.conf
  benma666-nginx:
    container_name: benma666-nginx
    image: benma666-nginx
    build:
      context: ./nginx
    ports:
      - "8091:8091"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/nginx:/benma666
      - ./data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/logs:/var/log/nginx
      - ./data/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - benma666-sjsj
    links:
      - benma666-sjsj
  benma666-sjsj:
    container_name: benma666-sjsj
    image: benma666-sjsj
    build:
      context: ./sjsj
      #dockerfile: dockerfile
    ports:
      - "8090:8090"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/sjsj:/benma666
    depends_on:
      - benma666-redis
      - benma666-mysql
    links:
      - benma666-redis
      - benma666-mysql
