version : '3.8'
services:
  benma666-mysql:
    container_name: benma666-mysql
    image: mysql
    build:
      context: ./mysql
    ports:
      - "3316:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]
    environment:
      MYSQL_DATABASE: 'sjsj2_zs'
      MYSQL_ROOT_PASSWORD: password
  benma666-redis:
    container_name: benma666-redis
    image: redis
    build:
      context: ./redis
    ports:
      - "6389:6379"
    volumes:
      - ./redis/conf/redis.conf:/benma666/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /benma666/redis/redis.conf
  benma666-nginx:
    container_name: benma666-nginx
    image: nginx
    build:
      context: ./nginx
    ports:
      - "8091:8091"
    volumes:
      - ./nginx/html/dist:/benma666/sjsj-qd
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - benma666-sjsj
    links:
      - benma666-sjsj
  benma666-sjsj:
    container_name: benma666-sjsj
    build:
      context: ./sjsj
      dockerfile: dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - benma666-redis
      - benma666-mysql
    links:
      - benma666-redis
      - benma666-mysql
